### PR TITLE
Dev/avicot/add ncs 5508

### PR DESCRIPTION
**Pull request by antoinevicot**

### CODE REVIEW

**Comment by netravnen** [comment]
@antoinevicot Please consider using [Git Pre-commit (Python Package)](https://pre-commit.com/). Running the included pre-commit "playbook" for this repo can help to detect validation errors before pushing to GitHub.

**Comment by netravnen** [comment]
```
$ pre-commit run                       
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
Check YAML files.........................................................Passed
Format YAML files........................................................Failed
- hook id: yamlfmt
- files were modified by this hook

device-types/Cisco/NCS-5508.yaml  Done

Lint YAML files..........................................................Passed
Run PyTest Case Checks...................................................Failed
- hook id: pytest
- exit code: 1

============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-7.4.4, pluggy-1.4.0 -- /home/netravnen/.virtualenvs/devicetype-library-zdvp/bin/python
cachedir: .pytest_cache
rootdir: /home/netravnen/projects/netbox/devicetype-library
collected 7 items                                                              

tests/definitions_test.py::test_environment SKIPPED (No changes to d...) [ 14%]
tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema0-A] FAILED [ 28%]
tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema1-M] FAILED [ 42%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-24X100G-SE.yaml-schema2-A] PASSED [ 57%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-36X100G-A-SE.yaml-schema3-A] PASSED [ 71%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-PWR-3KW-AC.yaml-schema4-A] FAILED [ 85%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-RP2-E.yaml-schema5-A] PASSED [100%]

=================================== FAILURES ===================================
_________ test_definitions[device-types/Cisco/NCS-5508.yaml-schema0-A] _________
0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0

During handling of the above exception, another exception occurred:
device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0
_________ test_definitions[device-types/Cisco/NCS-5508.yaml-schema1-M] _________
0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0

During handling of the above exception, another exception occurred:
device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0
_____ test_definitions[module-types/Cisco/NC55-PWR-3KW-AC.yaml-schema4-A] ______
tests/definitions_test.py:161: in test_definitions
    definition = yaml.load(content, Loader=DecimalSafeLoader)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/__init__.py:81: in load
    return loader.get_single_data()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/constructor.py:49: in get_single_data
    node = self.get_single_node()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:36: in get_single_node
    document = self.compose_document()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:55: in compose_document
    node = self.compose_node(None, None)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:82: in compose_node
    node = self.compose_sequence_node(anchor)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:111: in compose_sequence_node
    node.value.append(self.compose_node(node, index))
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:64: in compose_node
    if self.check_event(AliasEvent):
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/parser.py:98: in check_event
    self.current_event = self.state()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/parser.py:449: in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:116: in check_token
    self.fetch_more_tokens()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:247: in fetch_more_tokens
    return self.fetch_single()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:652: in fetch_single
    self.fetch_flow_scalar(style='\'')
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:666: in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:1151: in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:1238: in scan_flow_scalar_spaces
    raise ScannerError("while scanning a quoted scalar", start_mark,
E   yaml.scanner.ScannerError: while scanning a quoted scalar
E     in "<unicode string>", line 6, column 11:
E         - name: 'PS{module}''
E                 ^
E   found unexpected end of stream
E     in "<unicode string>", line 9, column 1:
E       
E       ^
=========================== short test summary info ============================
FAILED tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema0-A] - Failed: device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of typ...
FAILED tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema1-M] - Failed: device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of typ...
FAILED tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-PWR-3KW-AC.yaml-schema4-A] - yaml.scanner.ScannerError: while scanning a quoted scalar
=================== 3 failed, 3 passed, 1 skipped in 10.35s ====================

```

**Comment by netravnen** [comment]
```
$ pre-commit run                       
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
Check YAML files.........................................................Passed
Format YAML files........................................................Failed
- hook id: yamlfmt
- files were modified by this hook

device-types/Cisco/NCS-5508.yaml  Done

Lint YAML files..........................................................Passed
Run PyTest Case Checks...................................................Failed
- hook id: pytest
- exit code: 1

============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-7.4.4, pluggy-1.4.0 -- /home/<username>/.virtualenvs/devicetype-library-zdvp/bin/python
cachedir: .pytest_cache
rootdir: /home/<username>/projects/netbox/devicetype-library
collected 7 items                                                              

tests/definitions_test.py::test_environment SKIPPED (No changes to d...) [ 14%]
tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema0-A] FAILED [ 28%]
tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema1-M] FAILED [ 42%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-24X100G-SE.yaml-schema2-A] PASSED [ 57%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-36X100G-A-SE.yaml-schema3-A] PASSED [ 71%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-PWR-3KW-AC.yaml-schema4-A] FAILED [ 85%]
tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-RP2-E.yaml-schema5-A] PASSED [100%]

=================================== FAILURES ===================================
_________ test_definitions[device-types/Cisco/NCS-5508.yaml-schema0-A] _________
0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0

During handling of the above exception, another exception occurred:
device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0
_________ test_definitions[device-types/Cisco/NCS-5508.yaml-schema1-M] _________
0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0

During handling of the above exception, another exception occurred:
device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of type 'string'

Failed validating 'type' in schema['properties']['module-bays']['items']['properties']['position']:
    {'type': 'string'}

On instance['module-bays'][0]['position']:
    0
_____ test_definitions[module-types/Cisco/NC55-PWR-3KW-AC.yaml-schema4-A] ______
tests/definitions_test.py:161: in test_definitions
    definition = yaml.load(content, Loader=DecimalSafeLoader)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/__init__.py:81: in load
    return loader.get_single_data()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/constructor.py:49: in get_single_data
    node = self.get_single_node()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:36: in get_single_node
    document = self.compose_document()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:55: in compose_document
    node = self.compose_node(None, None)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:82: in compose_node
    node = self.compose_sequence_node(anchor)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:111: in compose_sequence_node
    node.value.append(self.compose_node(node, index))
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/composer.py:64: in compose_node
    if self.check_event(AliasEvent):
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/parser.py:98: in check_event
    self.current_event = self.state()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/parser.py:449: in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:116: in check_token
    self.fetch_more_tokens()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:247: in fetch_more_tokens
    return self.fetch_single()
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:652: in fetch_single
    self.fetch_flow_scalar(style='\'')
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:666: in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:1151: in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
../../../.virtualenvs/devicetype-library-zdvp/lib/python3.11/site-packages/yaml/scanner.py:1238: in scan_flow_scalar_spaces
    raise ScannerError("while scanning a quoted scalar", start_mark,
E   yaml.scanner.ScannerError: while scanning a quoted scalar
E     in "<unicode string>", line 6, column 11:
E         - name: 'PS{module}''
E                 ^
E   found unexpected end of stream
E     in "<unicode string>", line 9, column 1:
E       
E       ^
=========================== short test summary info ============================
FAILED tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema0-A] - Failed: device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of typ...
FAILED tests/definitions_test.py::test_definitions[device-types/Cisco/NCS-5508.yaml-schema1-M] - Failed: device-types/Cisco/NCS-5508.yaml failed validation: 0 is not of typ...
FAILED tests/definitions_test.py::test_definitions[module-types/Cisco/NC55-PWR-3KW-AC.yaml-schema4-A] - yaml.scanner.ScannerError: while scanning a quoted scalar
=================== 3 failed, 3 passed, 1 skipped in 10.35s ====================
```

**Comment by antoinevicot** [comment]
done thx :)

**Comment by danner26** [comment]
This appears to be a chassis for switches/etc. This should have `subdevice_role: parent` as well as `device-bays` for non-modules. There should be other models that are similar. @DanSheps  could you please guide them on this. You are much more familiar with these than I am!

**Comment by danner26** [comment]
For some reason I cannot update this branch, please update your branch against the master

**Comment by DanSheps** [comment]
> @DanSheps could you please guide them on this. You are much more familiar with these than I am!

At first glance, this all looks correct.  Typically Cisco chassis are still modules as they are simply large switches with replaceable line cards.

**Comment by danner26** [comment]
@antoinevicot when you get a moment please update your branch with the latest master version, then we can re-review

**Comment by danner26** [comment]
Thank you, can you also add `airflow` and `weight` if you have it. If not, please resolve that comment
These can often be found in the datasheets

**Comment by antoinevicot** [comment]
done thx 🥇

**Review by danner26 — APPROVED** [review]

**Pull request merged**
