### PR TITLE
Dell Networking Devices

### PR DESCRIPTION
**Pull request by tfl-jb**
Technical specs for the series can be found here: [Dell EMC PowerSwitch N2200-ON Series Switches](https://www.netsolutionworks.com/datasheets/dell-networking-n2200-powerswitch-specsheet.pdf )

### CODE REVIEW

**Comment by ryanmerolle** [comment]
@tfl-jb I added new lines to the end of each file to get past some CI checks.

**Comment by tfl-jb** [comment]
I think I will install the tools to run these test myself. I don't want to spam this PR with failed tests 😅

**Comment by danner26** [comment]
Do you still need this? @tfl-jb

**Comment by tfl-jb** [comment]
In general yes, but I haven't had the time to clean up my files. I will create a new PR when I'm ready, thanks!

**Comment by danner26** [comment]
Thanks @tfl-jb we would appreciate that!

**Pull request closed without merging**
