### PR TITLE
Module Test Improvements

### PR DESCRIPTION
**Pull request by danner26**
In reference to issue #1584 we have discovered a missing test case, it is now implemented and the affected files are fixed

### CODE REVIEW

**Comment by danner26** [comment]
Closes #1585 
Closes #1584

**Comment by DanSheps** [comment]
@danner26 Was busy yesterday and missed this.

I don't think this is a valid test, as it is perfectly reasonable (I do it often) to have same positions as long as they generate different component names.

For example:

Mod Bay 1:
  Name: PSU1
  Position: 1
Mod Bay 2:
  Name: PSU2
  Position: 2
Mod Bay 3:
  Name: FRU Uplink
  Position: 1

What we want is to be able to evaluate the final interface/power port/etc name and not the position and whether it is duplicated (which admittedly is not possible).  I think our tests for something like this should follow the upstream repo unique keys.

**Comment by danner26** [comment]
The test is to check for the case where PSU1 and PSU2 both share the same position

An `FRU Uplink` and `PSU1` with the same `position: 1` is valid and will pass the test case. Let me know if I am misunderstanding you

**Comment by DanSheps** [comment]
I didn't fully understand the code is I think the problem.  If it passes then all good IMO.

**Pull request merged**
