### PR TITLE
add/update parameters MikroTik & Zyxel

### PR DESCRIPTION
**Pull request by zupy666**
## manufacturer: **MikroTik**
Covers Devices and Modules.
### _Update Devices - CCR series:_
- CCR1009-7G-1C-1S+
- CCR1009-7G-1C-1S+PC
- CCR1009-7G-1C-PC
- CCR1009-8G-1S-1S+
- CCR1016-12G
- CCR1016-12S-1S+
- CCR1036-8G-2S+
- CCR1036-8G-2S+EM
- CCR1036-12G-4S-EM
- CCR1036-12G-4S
- CCR1072-1G-8S+
- CCR2004-1G-12S+2XS
- CCR2004-16G-2S+
- CCR2116-12G-4S+
- CCR2216-1G-12XS-2XQ

### _Update Devices - CRS series:_
- CRS106-1C-5S
- CRS112-8G-4S-IN
- CRS112-8P-4S-IN
- CRS125-24G-1S-2HnD-IN
- CRS125-24G-1S-IN
- CRS125-24G-1S-RM
- CRS212-1G-10S-1S+IN
- CRS226-24G-2S+RM
- CRS305-1G-4S+IN
- CRS309-1G-8S+IN
- CRS310-1G-5S-4S+IN
- CRS312-4C+8XG-RM
- CRS317-1G-16S+RM
- CRS326-24G-2S+RM
- CRS326-24S+2Q+RM
- CRS328-4C-20S-4S+RM
- CRS328-24P-4S+RM
- CRS354-48G-4S+2Q+RM
- CRS354-48P-4S+2Q+RM
- CRS504-4XQ-IN
- CRS518-16XS-2XQ-RM

### _Update Devices - CSS series:_
- CSS326-24G-2S+RM

### _Update Devices - RB series:_
- RB260GS
- RB260GSP
- RB941-2nD
- RB750r2
- RB750Gr3
- RB760iGS
- RB951G-2HnD
- RB960PGS
- RB1100AHx2
- RB1100AHx4
- RB1100AHx4 Dude Edition
- RB2011iL-IN
- RB2011iL-RM
- RB2011iLS-IN
- RB2011UiAS-IN
- RB2011UiAS-RM
- RB3011UiAS-RM
- RB4011iGS+RM
- RB5009UG+S+IN
- RB5009UPr+S+IN

### _Add Devices - CCR series:_
- CCR2004-16G-2S+PC
 
### _Add Devices - CSS series:_
- CSS610-1Gi-7R-2S+OUT
- CSS610-8G-2S+IN
- CSS610-8P-2S+IN

### _Add Devices - CRS series:_
- CRS109-8G-1S-2HnD-IN
- CRS305-1G-4S+OUT
- CRS310-1G-5S-4S+OUT
- CRS318-1Fi-15Fr-2S-OUT
- CRS318-16P-2S+OUT
- CRS326-24G-2S+IN
- CRS504-4XQ-OUT
- CRS510-8XS-2XQ-IN

### _Add Devices - RB series:_
- RB951Ui-2nD
- RB1200
- RB750UPr2
- RB750P-PBr2
- RB941-2nD-TC
- RB960PGS-PB

### _Add Modules:_
- MT-HotSwapFan
- PW48V-12V150W
- G1040A-60WF
- 12POW150

## manufacturer: **Zyxel**
Covers Devices.
### _Add Devices:_
- PMG1005-T20B
- FMG3005-R20A

### CODE REVIEW

**Comment by danner26** [comment]
Hey @zupy666 I am marking this PR as a draft. Once it is ready for review (after all builds pass), please mark it ready for review. Thank you

**Comment by zupy666** [comment]
Checked and supplemented with parameters a set of devices that intersect with RB.
I came across the example file "/devicetype-library/device-types/MikroTik/RB750r3.yaml", I did not find this model on the official mikrotik website.

@danner26 
In the instructions, I did not find an exact rule regarding the sequence of components. I apologize in advance. Let me know and I'll fix it if necessary.
And if you agree, I can review and supplement the other devices in the MikroTik folder.

**Comment by danner26** [comment]
Hey @zupy666 thanks for all of this so far.. One thing I am noticing among a few of the devices is that in the device picture port 13 is labelled as PoE/Boot. Does that mean that only port 13 is a PoE provider? If so, the power sourcing definitions need to move to interface 13

If they are all PoE ports then the PSE definitions need to be defined across all ports. Can you please confirm/verify the files you made modifications to and then let me know so I can re-review?

**Comment by zupy666** [comment]
Thanks for the note, the RB1100AHx2, RB1100AHx4 Dude Edition and RB1100AHx4 models have port 13 which is POE-IN. It is fixed in the templates.

**Comment by zupy666** [comment]
@danner26 
I am wondering about the reason for the failed validation e9dfe56 where the module level description was added. I don't see why this is treated as a negative, given the fact that the NetBox GUI form for import modules allows it to support the "description" parameter.
I temporarily removed the description.

**Comment by danner26** [comment]
Hey @zupy666 please leave this PR in a draft status until you are ready for it to be reviewed/merged. You are obviously actively working on this and there is no need for me to get alerts every single time you push a commit. Once you are ready for it to be reviewed, and thus merged to master, please mark it as ready to review. Thank you

**Comment by zupy666** [comment]
Hi @danner26 you beat me by two devices :) .. I checked all the devices and completed the missing data, as well as added some that I found on the official MIkrotik site.

Please see the comments I made in between.
I have now completed my part in full.

**Comment by zupy666** [comment]
I have now completed my part in full.

**Comment by danner26** [comment]
Thanks @zupy666 I appreciate all of your work

I got over 100 emails this morning about all of your pushes lmao. I will start reviewing the changes

**Comment by zupy666** [comment]
@danner26 Apologies for the morning email wake-up :) 
Please let me know if anything needs to be updated.

**Comment by danner26** [comment]
No worries at all, I will post a review/notate any changes or questions on each file using the GitHub review process when I am done

**Comment by danner26** [comment]
Hey @zupy666 a few minor things, if you could put `power-ports`, `console-ports`, `module-bays`, etc above the `interfaces` that would be great.. If you want, you can invite me to your fork and I can make these changes for you. You are of course welcome to do them as well.

**Comment by zupy666** [comment]
In the Mikrotik world, SFP+1 is named as sfp-sfpplus1. When adding parameters to existing files, I did not change what the predecessors stated.
As for the AC or DC power-ports, most devices have redundant or even multiple redundant power supplies, where AC is usually not named on the case, while DC is even more confusing :).

I suggest a step-by-step solution.
1. Positioning of assemblies
2. Remove description and label where they are not needed
3. Systematic naming of port interfaces
4. Various (because we will find something soon :) )

**Comment by danner26** [comment]
In regards to the SFP naming, sounds good to me!

Take a look at CCR2004-16G-2S+PC.yaml, that one specifically is 2 `dc-terminal` ports. Really these need to match exactly what either the config or the manufacturer calls them, and if all else fails a generic fallback such as `PSU11. That being said, the type of power input needs to be correct in each definition file.

**Comment by zupy666** [comment]
Before I start shifting the assemblies. Do you have the exact sequence documented somewhere? I assume that:
1. interfaces
2. console-ports
3. console-server-ports
3. module-bays
4. device-bays
5. power-ports
6. power-outlets
7. front-ports
8. rear-ports

**Comment by danner26** [comment]
Yup then what I said is how I usually go about it, but again it is not set in stone

**Comment by zupy666** [comment]
@danner26 managed to review and rework the CCR series... can I ask you for a review and comment before I even tackle the others. Thank you.

**Comment by zupy666** [comment]
I would like to ask you for a hint. I can't find the reason for the commit error.

**Comment by danner26** [comment]
Hey @zupy666 any reson you closed this?

**Comment by zupy666** [comment]
@danner26 Can you help me solve it? Or what do you suggest?

**Comment by danner26** [comment]
We have updated the validation and testing process such that it will require everyone to adhere to the same standards setout by the pre-commit procedure/tests. The easiest way to fix issues with this PR is to:

1. Merge master into this branch if you have not already
2. Clone the codebase using VSCode, and then switch to this branch
3. Install the repository requirements using `pip3 install -r requirements.txt`
4. Run pre-commit install `pre-commit install`
5. Run pre-commit tasks `pre-commit run -a`

This should A) format yaml files appropriately, and B) ensure that all files adhere to the test steps

**Comment by danner26** [comment]
Alternatively you can send me an invite to work on your fork of this repo, and I can make the necessary changes to fix formatting issues

**Pull request closed without merging**
