### PR TITLE
Update APC NMC module ports

### PR DESCRIPTION
**Pull request by squintfox**
Updated missing ports on APC NMC modules

### CODE REVIEW

**Comment by danner26** [comment]
Generally modules will use the module number in the name, to avoid collisions with on board interfaces. You should probably modify the interfaces and console names so that this doesnt occur

**Comment by squintfox** [comment]
@danner26 I think I understood what you asked for?  Let me know if I didn't get it right.

**Comment by danner26** [comment]
Not quite, sorry about that. If you take a look at [the C9300-NM-4G](https://github.com/netbox-community/devicetype-library/blob/master/module-types/Cisco/C9300-NM-4G.yaml) we have `{module}` in the name. Once this module is loaded into a devices module bay, lets call that module bay `1` in this case (but it could be anything such as `M1`, `MOD1`, etc), the interfaces associated with the module will get automatically added to the device called `GigabitEthernet1/1/1`, `GigabitEthernet1/1/2` and so forth

If the module bay is named `MOD1` and we loaded the C9300-NM-4G, you would see interfaces called `GigabitEthernet1/MOD1/1`, etc.

What this does is prevents clashing of non-unique interface/port names.

**Comment by squintfox** [comment]
@danner26 OK, I think I understand.  Should be good now.

**Comment by danner26** [comment]
That should work!

**Pull request merged**
