### PR TITLE
Adding a couple of UniFi device things

### PR DESCRIPTION
**Pull request by tobiasehlert**
- renaming files (to match part_number)
- removing unused mgmt_only flag from es-templates
- adding all UniFi APs
- adding UniFi UDM
- adding 4 more UniFi switches

PR is addition to https://github.com/netbox-community/devicetype-library/pull/171

### CODE REVIEW

**Comment by DanSheps** [comment]
Please correct the failures

**Comment by tobiasehlert** [comment]
@DanSheps the build log is too old, so can't see, what that could have been.

**Comment by DanSheps** [comment]
```
================================================================================================================= FAILURES =================================================================================================================
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-EDU.yaml] _________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-EDU.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-HD.yaml] __________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-HD.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_______________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-IW-PRO.yaml] ________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-IW-PRO.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-IW.yaml] __________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-IW.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-LITE.yaml] _________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-LITE.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-LR.yaml] __________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-LR.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-PRO.yaml] _________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-PRO.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-AC-SHD.yaml] _________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-AC-SHD.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-BeaconHD.yaml] ________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-BeaconHD.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-FlexHD.yaml] _________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-FlexHD.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-IW-HD.yaml] __________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-IW-HD.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
___________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-LR.yaml] ___________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-LR.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-nanoHD.yaml] _________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-nanoHD.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-Outdoor+.yaml] ________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-Outdoor+.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-Outdoor5.yaml] ________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-Outdoor5.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
__________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-PRO.yaml] ___________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-PRO.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
___________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP-XG.yaml] ___________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP-XG.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
____________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UAP.yaml] _____________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UAP.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
_________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UWB-XG-BK.yaml] __________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UWB-XG-BK.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
___________________________________________________________________________________________ test_definition[device-types\\Ubiquiti\\UWB-XG.yaml] ___________________________________________________________________________________________
'' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''

During handling of the above exception, another exception occurred:
device-types\Ubiquiti\UWB-XG.yaml failed validation: '' is not one of ['parent', 'child']

Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}

On instance['subdevice_role']:
    ''
```

**Comment by ryanmerolle** [comment]
This is stale.  Please reopen if you want to work on this.

**Pull request closed without merging**
