### PR TITLE
Brocade FiberChannel (G610, G620 & G630)

### PR DESCRIPTION
**Pull request by suom1**

### CODE REVIEW

**Comment by suom1** [comment]
@ryanmerolle I might be doing something wrong, but I can't figure out what's wrong with the files commited :/

**Comment by suom1** [comment]
@michaelklose this was merged into 3.1.0 which was released today! :)

**Comment by michaelklose** [comment]
Validation should work now. Can you rerun the validation checks?

**Comment by suom1** [comment]
Hmm. this didn't go as expected. Will recrate PR. :(

**Pull request closed without merging**
