### PR TITLE
Add Palo Alto PA-410,PA-440,PA-450,PA-460

### PR DESCRIPTION
**Pull request by stuntguy3000**
Re-opening from https://github.com/netbox-community/devicetype-library/pull/1365 due to corrupted branch :)

### CODE REVIEW

**Comment by danner26** [comment]
Hey @stuntguy3000, yeah please remove the USB interfaces that are not used for console access

**Comment by stuntguy3000** [comment]
Sounds good, fixed.

**Comment by danner26** [comment]
Do you have weight and airflow information? If you can, please add `weight`/`weight_unit` as well as `airflow`. The datasheets usually have this information if you wouldnt mind adding it

**Comment by stuntguy3000** [comment]
Sorry - looks like I lost that information in my branch corruption. Will review and add tomorrow.

**Comment by stuntguy3000** [comment]
Scratch that, had the information on hand. Added/pushed.

**Review by danner26 — APPROVED** [review]

**Pull request merged**
