### PR TITLE
Create V1910-48G

### PR DESCRIPTION
**Pull request by LHBL2003**
New Switch

### CODE REVIEW

**Comment by danner26** [comment]
Do you still need this? @LHBL2003

**Comment by LHBL2003** [comment]
> Do you still need this? @LHBL2003

I have created these device types in Netbox, at least for me, since this was not available.

**Comment by danner26** [comment]
If you still want to contribute we would be happy to review it again. The original maintainers are busy but I am here to make sure the PRs get worked on
If you would like to contribute please feel free to reopen this PR, update your branch against our master, and then fix any issues. From there I will be happy to review it

**Comment by LHBL2003** [comment]
What is meant by master?
Is there a master template for device types against which I should compare my yaml file?

**Comment by danner26** [comment]
@LHBL2003 please check the CI run and fix the issues defined. You can use `pre-commit run -a` in your local dev environment to see the issues before committing

**Comment by danner26** [comment]
Hello @LHBL2003, are you able to work on this?

**Comment by LHBL2003** [comment]
https://github.com/netbox-community/devicetype-library/pull/1044

I have changers —- to begin in patch-3

**Comment by danner26** [comment]
Hello @LHBL2003 we have merged that request
There are now conflicts within this branch. Please fix those issues and let us know if you need assistance

**Comment by LHBL2003** [comment]
I closed this one because we adjusted everything in patch 3 https://github.com/netbox-community/devicetype-library/pull/1044.

**Pull request closed without merging**
