### PR TITLE
Add Ubiquiti INS-3AF-O-G PoE adapter

### PR DESCRIPTION
**Pull request by BarbarossaTM**

### CODE REVIEW

**Comment by danner26** [comment]
Hello @BarbarossaTM I do not think this is the correct way to model this. Instead, you should have 1 interface with PoE Mode set to Power Delivery `PD`, and the second interface with PoE Mode set to Power Supply `PSE`

**Comment by BarbarossaTM** [comment]
Hm, I can see why you would want to model it this way. For me there are two reasons for rather choosing Front/Rear Port:

a) In my understanding an Interface terminates an L2 connection, which doesn't happen here, L2+-wise this thing is totally transparent, arguebly even L1-wise.
b) I want to be able to trace from the switch to the connected WiFi backhaul gear / see it directly on the switches interfaces page / the API, which I loose if these are interfaces.

What do you think?

**Comment by danner26** [comment]
Hmm I see all of your points, let me pose this to the maintainers and lets see what the collective thinks

**Comment by BarbarossaTM** [comment]
Hey @danner26, did the collective come up with a verdict? :-D

**Comment by danner26** [comment]
We are torn on it, pretty much 50/50. So as a last ditch effort, just to cover all of my bases, I am going to pose the question to the community.. If I dont reach back out in a few days please ping me again! I am sorry for the delay

**Comment by danner26** [comment]
[This discussion](https://github.com/netbox-community/devicetype-library/discussions/1235) includes the poll

**Comment by danner26** [comment]
Alright we are going with what you have! The majority has decided. Thanks for waiting while we figured that out

**Pull request merged**
