### PR TITLE
add Cisco IE 3000 series switches

### PR DESCRIPTION
**Pull request by abu-rehan**
Added three templates from Cisco IE 3000 series.

### CODE REVIEW

**Review by danner26 — CHANGES_REQUESTED** [review]

**Comment by danner26** [comment]
Device-bays are used when devices physically slot into another device. It does not appear this is the case. Can you please clarify this?

**Comment by abu-rehan** [comment]
> Device-bays are used when devices physically slot into another device. It does not appear this is the case. Can you please clarify this?
The devices have to be physically combined. The child device cannot be a standalone device. Device Bay, we thought would be the most appropriate way of modelling it. If it doesn't look right, you can close this pull request. Also if you have encountered IE 3000 before in netbox, do you have tips on how to model them?

**Comment by DanSheps** [comment]
These are modules, not devices and should be modelled using module bays.

Are you not using 3.6 for NetBox?

**Comment by abu-rehan** [comment]
Yes we are using netbox 3.6 and above. We are closing this PR for now. We will try out these devices as modules and see if that works fine.

**Pull request closed without merging**
