### PR TITLE
Add two ActionTec DSL modems.

### PR DESCRIPTION
**Pull request by garbled1**
There really is no good interface type for POTS so I added them as 100's.

### CODE REVIEW

**Comment by wtinetworkgear** [comment]
We defined our POTS modem lines as


  - name: Modem
    type: rj-11?




________________________________

**Comment by garbled1** [comment]
That's not an interface type though, it's only available if I pick something like console port or front/rear port.  I kinda wanted to be able to assign IP's and such to it.   Sadly there are a few interface types missing for older equipment.  :)  I should file something on that...

**Comment by DanSheps** [comment]
Please change the interface type to "other"

**Comment by garbled1** [comment]
I don't see other listed in tests/schema.json.  Doesn't that have to be updated first?

**Comment by DanSheps** [comment]
It looks like it needs to be updated, perhaps @ryanmerolle can handle that.

**Comment by ryanmerolle** [comment]
@DanSheps @garbled1 I added the missing "other" interface as long as any other missing interfaces to the schema.json file.  You can make your updates and I will merge the PR.

**Pull request merged**
