### PR TITLE
Add a tonne of images and a few Aruba devices

### PR DESCRIPTION
**Pull request by rtm516**
New devices:
 - Aruba 7008 (JX927A)
 - Aruba 7024 (JW682A)

140 new images

### CODE REVIEW

**Comment by lucatortiglione** [comment]
Where did you get the images ?
I'd like to add them for Cisco devices

**Comment by rtm516** [comment]
> Where did you get the images ? I'd like to add them for Cisco devices

Visio stencils, wrote a VBA script to export a png of every shape in the loaded vss file. Then combined that with a simple python script to load those images in for existing yml files and put them in the correct location.

Heres the visio script for doing it, along with a few instructions at the top of the file
[Visio-ExportAllShapes.vba.txt](https://github.com/netbox-community/devicetype-library/files/14089727/Visio-ExportAllShapes.vba.txt)

Looks like Ciscos are here https://www.cisco.com/c/en/us/products/visio-stencil-listing.html

**Comment by rtm516** [comment]
Not stale

**Comment by robinreinhardt** [comment]
looks very nice!

**Review by danner26 — APPROVED** [review]

**Pull request merged**
