### PR TITLE
Added Wall boxes with 2, 3, 4 and 6 UTP plugs.

### PR DESCRIPTION
**Pull request by jnovak-netsystemcz**
Added Wall boxes with 2, 3, 4 and 6 UTP plugs.
They can be used for documenting physical wiring.

### CODE REVIEW

**Comment by danner26** [comment]
A rack mounted wall box? I am confused what this actually is
Can you send a link to what you are representing here?

**Comment by jnovak-netsystemcz** [comment]
No, it is non-rack device. We use plenty of different types so I created it as generic. There is example:

https://www.vseprowifi.cz/utp-kabely-konektory-zasuvky-w-star-zasuvka-utp-2xrj45-na-zed-narazeci-cat5e-kompletni-na-stenu-p-805.html

**Comment by danner26** [comment]
You have `u_height: 1.0` set on these. If they are not rack mounted then they should be `u_height: 0`

**Comment by jnovak-netsystemcz** [comment]
I see. Set to 0.

**Comment by danner26** [comment]
I think you should omit both `is_full_depth` and `airflow`. Airflow isnt really important with these wall mounted utp ports, and is_full_depth defaults to true anyway.

**Comment by jnovak-netsystemcz** [comment]
Done

**Comment by danner26** [comment]
@jnovak-netsystemcz I was talking with someone else, it makes sense to actually mark these as `is_full_depth: false` since I guess if they get placed in a rack theyre not a full depth item. I am sorry about that.. Once more change and we should be good to go

**Comment by jnovak-netsystemcz** [comment]
I agree with it. Done.

**Comment by danner26** [comment]
Changes merged! Thanks @jnovak-netsystemcz

**Pull request merged**
