### PR TITLE
Create RB951Ui-2HnD.yaml

### PR DESCRIPTION
**Pull request by avgosha**
Added template for RB951Ui-2HnD router in desktop case.

### CODE REVIEW

**Comment by antonalekseev** [comment]
> Wifi is not yet supported by NetBox

@ryanmerolle, is that actually true? Support for WLAN interfaces was added long time ago in https://github.com/netbox-community/netbox/commit/68ebe85a98528b6db0582b0fc49de968dbd6198b. I agree, there is still no entity to represent WLAN connections similar to cables for a wired ones, but at least IP address can be assigned to an interface.

**Comment by antonalekseev** [comment]
Also, the device has a coaxial power connector which is not a valid Netbox power connector type yet, and there is no generic type as well (as per https://github.com/netbox-community/netbox/issues/792).

**Comment by ryanmerolle** [comment]
Good find @antonalekseev I stand corrected.  I forgot about that.

I was more speaking to a model overall that also represents WLAN connections similar to cables.  We can proceed given the interface types are present in NetBox core.


> @ryanmerolle, is that actually true? Support for WLAN interfaces was added long time ago in https://github.com/netbox-community/netbox/commit/68ebe85a98528b6db0582b0fc49de968dbd6198b. I agree, there is still no entity to represent WLAN connections similar to cables for a wired ones, but at least IP address can be assigned to an interface.

**Comment by danner26** [comment]
Do you still need this? @avgosha

**Comment by avgosha** [comment]
Yes, please add it.Kind Regards,Alexey Gosha4 янв. 2023 г., в 18:12, Daniel W. Anner ***@***.***> написал(а):﻿
Do you still need this? @avgosha

**Comment by danner26** [comment]
Hello @avgosha I have reopened this, I will review it and comment back with any issues

**Comment by danner26** [comment]
Hello @avgosha have you had a chance to review this yet?

**Pull request closed without merging**
