### PR TITLE
Add 2530-8G and updated 2530-8

### PR DESCRIPTION
**Pull request by francesco-noc**
Hi,

actual file 2530-8G has part number J9783A which identifies Aruba 2530-8 Switch. I updated part_number field and added 2530-8 yml file.

Source: https://support.hpe.com/hpesc/public/docDisplay?docId=emr_na-c03624915

### CODE REVIEW

**Comment by danner26** [comment]
It looks like the `2530-8` has a dc terminal power plug, can you please confirm this/provide a link to where it uses `iec-60320-c14`?
Same question for the `2530-8G`?

**Comment by francesco-noc** [comment]
Unfortunately I'm not able to find any official documentation or images on hpe.com.
Images in many e-stores  portray 2530-8 with dc terminal power plug, as you state. Sorry for mistake.
2530-8G has C14, I have it on hand.

**Comment by danner26** [comment]
Thanks for the changes @francesco-noc!

**device-types/Aruba/2530-8.yaml**
Do you happen to have `airflow` and `weight` information? If so, could you please add it
If possible, can you please add a comment on the device in markdown format with a link to the datasheet?

**device-types/Aruba/2530-8G.yaml**
Do you happen to have `airflow` and `weight` information? If so, could you please add it
If possible, can you please add a comment on the device in markdown format with a link to the datasheet?

Otherwise everything looks good! Thank you. Let me know once you are ready for me to review again

**Comment by francesco-noc** [comment]
Sorry, I didn't understand how to add link to the datasheet.

https://support.hpe.com/hpesc/public/docDisplay?docId=emr_na-c03624915

**Comment by danner26** [comment]
Hello @francesco-noc, please take a look at the most recent merge. As decided in [this discussion](https://github.com/netbox-community/devicetype-library/discussions/1137) for HPE and Aruba, we have merged Aruba into HPE. Let me know if you need any help

**Comment by danner26** [comment]
Hey @francesco-noc looks like those files are already in the master branch

**Comment by danner26** [comment]
So far looks good, let me know when you are ready for me to review

**Comment by francesco-noc** [comment]
I'm ok with these two devices.

**Pull request merged**
