### PR TITLE
adding FX Modular Architecture Components

### PR DESCRIPTION
**Pull request by bbrk364**
I like to adding the FX Modular Architecture Components into the labrary

### CODE REVIEW

**Review by DanSheps — CHANGES_REQUESTED** [review]
Could you break these out into separate PR's per manufacturer?

**Review by bbrk364 — COMMENTED** [review]
adding PowerEdge FX2 2BAY

**Review by bbrk364 — COMMENTED** [review]
adding PowerEdge FX2 4BAY

**Review by bbrk364 — COMMENTED** [review]
adding PowerEdge FX2 8BAY

**Review by bbrk364 — COMMENTED** [review]
adding PowerEdge FX2s 2BAY

**Review by bbrk364 — COMMENTED** [review]
adding PowerEdge FX2s 4BAY

**Review by bbrk364 — COMMENTED** [review]
adding PowerEdge FX2s 8BAY

**Comment by DanSheps** [comment]
I am sorry, after a quick review, there are just too many errors with some of the Cisco devices.  I don't think we can accept this as is.

**Comment by DanSheps** [comment]
If you wish to resubmit, I would recommend at least breaking it out per manufacturer

**Comment by jeremystretch** [comment]
I agree with @DanSheps; this PR has a _ton_ of changes in it, apparently dating back five months? In general, pull requests should focus on a central theme (e.g. fixing one attribute on all devices, or adding several devices for a particular manufacturer) and avoid packing too many changes into a single request. This ensures that they can be reviewed efficiently, and allows approved changes to be merged without needing to wait for problems elsewhere in the PR to be addressed.

**Pull request closed without merging**
