### PR TITLE
Create Summit X460-48T.yaml

### PR DESCRIPTION
**Pull request by renaniam**
Template Extreme Neworks X460-48T Switch all 5 Bays (2 PSU + 1 FAN + 1 XGM3S + 1 VIM-2)

### CODE REVIEW

**Comment by danner26** [comment]
Hey @renaniam 
For port 45-48, do they default to SFP or 1000BASE-T? Whichever their default is should be defined in this definition.

Also, just confirming, the port names in the config are `1`, `2`, etc? Or do they have full reference names?

**Comment by renaniam** [comment]
> Hey @renaniam For port 45-48, do they default to SFP or 1000BASE-T? Whichever their default is should be defined in this definition.
> 
> Also, just confirming, the port names in the config are `1`, `2`, etc? Or do they have full reference names?
@danner26 Really our tests on switch doesn't shows combo ports. 

Thank you!

**Comment by danner26** [comment]
No problem, did you mean to close this or was it an accident? If you want to merge this, please reopen the commit.

**Comment by danner26** [comment]
Hey @renaniam last thing. For the port names, in the device configuration are they actually configured using the names `1`, `2`, etc? Or do they have full reference names?

For interface names we try to make sure they are referenced as exactly what the devices use, so for instance in Cisco land they are called `GigabitEthernet1/0/1`. They can also be configured with `ge1/0/1` but we try to make sure these are the full configuration names. If you could send a snippet of the configuration with the device names that would be appreciated

**Comment by danner26** [comment]
Hey @renaniam just nudging you to see if you have time to work on this again

**Comment by mayafox** [comment]
how is this different then the X460-G2-48P-10GE4 already present?

**Comment by renaniam** [comment]
@danner26 Hi again! Sorry for my long time to answer!

1st Question - Yes, the interfaces on this switch are named as just a number, it did haunt me too! When the device are in stacking them the interfaces starts with a "slot":"interface number" the "master" will be the 1 and we will get interfaces like 1:[1-52] and the second stacking switch we will get interfaces like 2:[1-52].

2nd Question - Yes Summit X460-48T are a stackable, but not a chassis switch. I put as a Parent Device cause the switch has a 1 Fan Module, Slot A and Slot B. (3 Module Bays).

Slot A - XGM3 Modules (XGM3S-2xf (add 2SFP+), XGM3SB-4SF (add 4 SFP)or XGM3SB-2SF (add 2SFP))
Slot B - Just to Stacking Modules (add 2 Ports just for stacking, but are a cable config there's no software config)

Best regards!

**Comment by danner26** [comment]
Hello @renaniam for question 1, sounds goods!

Question 2, as a stackable device this is not a parent then. I have removed that definition for you. Please review the changes and if everything looks good we can merge this! Thanks

**Comment by danner26** [comment]
Hello @renaniam did you get a chance to review my changes yet?

**Pull request closed without merging**
