### PR TITLE
Huawei s5700

### PR DESCRIPTION
**Pull request by quequiel**
Huawei S5731-S24T4X and modules
Huawei S5735-L24P4X-A1

### CODE REVIEW

**Comment by danner26** [comment]
Please correct the failures and push those changes. You can also locally use pre-commit to have it find and fix issues
If you need more assistance please let me know

**Comment by danner26** [comment]
@quequiel any reason you dont have any `power-ports:`?

**Comment by quequiel** [comment]
> @quequiel any reason you dont have any `power-ports:`?

Hi @danner26 S5731 has modular power supplies, no power ports embedded on the device. I created PAC600S12-DB as a module and  S5731 has 2 module bays for power supplies.

Thanks for jumping in and checking PRs!!

**Comment by danner26** [comment]
Thanks for the clarification! I appreciate it
Go ahead and mark this PR as ready for review and we can merge it

**Pull request merged**
