### PR TITLE
Corrected height unit on UCS C460 M4 (all checks passed)

### PR DESCRIPTION
**Pull request by fknorn**

### CODE REVIEW

**Comment by fknorn** [comment]
Apologies, missed updating the height unit when I created the device earlier today.

**Review by ravench — COMMENTED** [review]
Looks correct
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c460-m4-rack-server/datasheet-c78-730907.html

**Comment by fknorn** [comment]
> Looks correct https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c460-m4-rack-server/datasheet-c78-730907.html

How do you mean? The current value of 1RU is wrong, it should be 4RU, hence my correction...

To quote from the Data Sheet:

> The Cisco UCS C460 M4 is a four-rack-unit (4RU) rack server supporting ...

**Comment by ravench** [comment]
> > Looks correct https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c460-m4-rack-server/datasheet-c78-730907.html
> 
> How do you mean? The current value of 1RU is wrong, it should be 4RU, hence my correction...
> 
> To quote from the Data Sheet:
> 
> > The Cisco UCS C460 M4 is a four-rack-unit (4RU) rack server supporting ...

Yes, that's what I'm trying to say.
Linking the datasheet helps maintainers verify your change without too much effort.

**Review by harryajc — APPROVED** [review]
Not Sure how I missed that too, I guess I'm used to everything being 1U :)

**Pull request merged**
