### PR TITLE
Update RB750r2.yaml

### PR DESCRIPTION
**Pull request by vitor369789**

### CODE REVIEW

**Comment by vitor369789** [comment]
arumando

**Comment by danner26** [comment]
Hello @vitor369789 I have updated the product definition since there were multiple issues I noticed. First, the power is a DC terminal according to [this product page](https://mikrotik.com/product/RB750r2). I have also added the applicable `airflow`, full depth, and `u_height`. Lastly I added a device comment with a link to the product page

Please review these changes, and upon you verbally approving them I will merge them in. Thanks!

**Comment by danner26** [comment]
Hello @vitor369789 do you have any time to work on this yet?

**Comment by danner26** [comment]
Hello, unfortunately today we had to make a change to the schema in which weight is defined by. The upstream NetBox API requires weight to be passed to it in the following format:
```
weight: 12.01
weight_unit: lb
```

Due to this change, I have updated your branch against the current master. This might require you to update your PR, if you had weight currently defined, so that your PR is in-line with the new weight schema. If you have any issues, please let me know or refer to [this PR](https://github.com/netbox-community/devicetype-library/pull/1187) for more information.

**Comment by zupy666** [comment]
Hello, I just noticed this ticket, I would like to inform you that I have updated the parameters for the RB750r2 equipment as part of PR#1196

**Comment by danner26** [comment]
Hello, we have released a new set of tests and features to assist with properly creating definition files for the DeviceType-Library. These tests will ensure that all files conform to a standardized format and contain valid data. Over the coming weeks we will be adding more tests to handle other currently undefined cases. If you notice anything that you believe is a bug, please @ me in a comment and details what you think is incorrect.

Along with additional test cases we have added a feature that will annotate why tests fail. To access these annotations after a test has completed, please navigate to the _Files changed_ tab within your PR. At the very bottom of the page you will see a list of errors along with the filename in question and the error which was found.

With all this being said, if your PR is validated then great! Please @ me me so I can review it further! If your PR is not valid, please review the issues and correct them; in the meantime I will mark your PR as a draft. After correcting the issues and recieving a valid status, please mark the PR as ready to be reviewed. Thank you!

**Review by danner26 — APPROVED** [review]

**Pull request merged**
