### PR TITLE
Add Huawei CloudEngine S5732-H48XUM2CC model + PSU + FAN

### PR DESCRIPTION
**Pull request by BarbarossaTM**

### CODE REVIEW

**Comment by BarbarossaTM** [comment]
Hey @DanSheps is there anything that needs to happen for this PR to be merged? Thanks :-)

**Comment by danner26** [comment]
@BarbarossaTM can you please make sure all yaml files have a newline at the end of the file? Thank you.

**Comment by BarbarossaTM** [comment]
@danner26 Sure, done :-)

**Comment by danner26** [comment]
Sorry @BarbarossaTM  I just meant a single newline.. Do you know how to use `pre-commit run`? If so, that will fix the issues for you. Otherwise you can try manually resolving them or you can give me access to your forked repo and I can fix them for you

**Comment by BarbarossaTM** [comment]
Oh :-D This should fix it now, ran `pre-commit run` and it seemed happy now. Thanks!

**Comment by danner26** [comment]
All looks good now, thanks @BarbarossaTM 
I will merge this soon

**Pull request merged**
