### PR TITLE
Aruba-EdgeConnect

### PR DESCRIPTION
**Pull request by florianschendel**
Added Aruba SDWAN appliances as new device-type

e.g. ec-m

ec == EdgeConnect
m ==  model medium (performance class)

Details are are available on the Aruba website

https://www.arubanetworks.com/techdocs/sdwan/media/hardware/reference/EdgeConnect-Hardware-Reference-latest.pdf

### CODE REVIEW

**Comment by florianschendel** [comment]
@jeremystretch @ryanmerolle 
Hi, was my pull request wrong? Can someone merge my request, please?

**Comment by ryanmerolle** [comment]
For first time contributors to a repo, github has a manual process to approve/trigger the github CI/CD.

I just never saw a notification that I needed to approve you.  Every commit for this PR will require an approval until your first PR gets merged.

**Comment by ryanmerolle** [comment]
Now that it ran, it looks like yamllint's opinionated structure enforcement is looking for you to make some yaml changes with indenting (2 spaces for each nested item) among some other iterms of feedback.

https://github.com/netbox-community/devicetype-library/runs/6179632406?check_suite_focus=true

**Comment by ryanmerolle** [comment]
@florianschendel you need to commit and push your changes if you updated them locally.

**Comment by florianschendel** [comment]
@ryanmerolle I saw there where some other great typing errors. I just fixed it in [47119fd](https://github.com/netbox-community/devicetype-library/pull/773/commits/47119fd974e61c78400ddd60905398d09b0b1d92)

**Pull request merged**
