### PR TITLE
Add BDCOM-S2900-48P6X-PoE

### PR DESCRIPTION
**Pull request by aleferrariuy**
Chinese brand BDCOM switch.
S2900-P L3 Lite series.
Model S2900-48P6X with PoE.

### CODE REVIEW

**Review by aleferrariuy — COMMENTED** [review]
Syntax correction.

**Comment by aleferrariuy** [comment]
I don't realize where the problem is.

**Comment by kbrown900** [comment]
It took a lot of digging but my issues ended up being from my yaml config for a couple of the additions. I ran all the pre-check scripts which helped give some additional info.

**Comment by danner26** [comment]
Running `pre-commit run -a` gives us the following:

```
___ test_definitions[device-types/BDCOM/S2900-48P6X-PoE.yaml-schema417-skip] ___
device-types/BDCOM/S2900-48P6X-PoE.yaml has slug "bdcom-s2900-1930-48p6x-poe". Does not end with the model "bdcom-s2900-48p6x-poe" or part_number "s2900-p"
___ test_definitions[device-types/Cisco/N3K-C3064Q-10GE.yaml-schema817-skip] ___
device-types/Cisco/N3K-C3064Q-10GE.yaml has a duplicate slug: "cisco-n3k-c3064q-10ge"
_ test_definitions[device-types/Watchguard/Firebox-M370.yaml-schema2880-skip] __
device-types/Watchguard/Firebox-M370.yaml has a duplicate slug: "watchguard-firebox-m370"
__ test_definitions[device-types/Watchguard/Firebox-T80.yaml-schema2881-skip] __
device-types/Watchguard/Firebox-T80.yaml has a duplicate slug: "watchguard-firebox-t80"
```

**Comment by danner26** [comment]
Per the failures, you have duplicate device slugs. if the devices are already defined in the repo you will need to remove them and/or merge your changes

Also, the BDCOM/S2900-48P6X-PoE.yaml has an incorrect slug. It should either be `bdcom-s2900-48p6x-poe` or bdcom-s2900-p`

**Pull request closed without merging**
