### PR TITLE
Create 3810m-48g-poe-1-slot.yaml

### PR DESCRIPTION
**Pull request by cmcknz77**
Create 3810M 48G PoE+ modularised switch

### CODE REVIEW

**Review by cmcknz77 — COMMENTED** [review]
Update YAML formatting

**Review by cmcknz77 — COMMENTED** [review]
Include Airflow

**Comment by ryanmerolle** [comment]
Get rid of the empty fields please because they are triggering the CI fails.

**Comment by danner26** [comment]
Do you still need this? @cmcknz77

**Pull request closed without merging**
