### PR TITLE
Add ArubaOS switch modules for 2920/2930/3810 series switches

### PR DESCRIPTION
**Pull request by cmcknz77**
Add ArubaOS switch modules for 2920/2930/3810 series switches

### CODE REVIEW

**Review by cmcknz77 — COMMENTED** [review]
Updated YAML Formatting

**Review by cmcknz77 — COMMENTED** [review]
Updated YAML Formatting

**Comment by ryanmerolle** [comment]
get rid of the empty keys please

**Comment by danner26** [comment]
Do you still need this? @cmcknz77

**Pull request closed without merging**
