### PR TITLE
Update PowerEdge_R640.yaml

### PR DESCRIPTION
**Pull request by dmcken**
Fix error with import:
[{"__all__":["Subdevice role of device type (PowerEdge R640) must be set to \"parent\" to allow device bays."]},{"__all__":["Subdevice role of device type (PowerEdge R640) must be set to \"parent\" to allow device bays."]},{"__all__":["Subdevice role of device type (PowerEdge R640) must be set to \"parent\" to allow device bays."]}]

### CODE REVIEW

**Comment by DanSheps** [comment]
This should be rewritten to use modules instead of device bays

**Review by DanSheps — CHANGES_REQUESTED** [review]
Rewrite for modules instead of device bays

**Comment by dmcken** [comment]
Drop the parent then?

**Comment by dmcken** [comment]
I ask since this will then require positions which I don't know.

**Review by DanSheps — APPROVED** [review]

**Pull request merged**
