### PR TITLE
Additions of Avocent, Cisco ACI, and Meraki 

### PR DESCRIPTION
**Pull request by jemery27**

### CODE REVIEW

**Comment by jeremystretch** [comment]
Validation is failing because you've defined an empty subdevice role:

```
subdevice_role: ''
```

Just omit these and other fields you've set to empty strings: If they have no value there's no reason to include them.

**Comment by jemery27** [comment]
Ok cool thanks - just FYI the reason I included them is I created the templates in netbox and exported.

**Comment by jeremystretch** [comment]
``
  allocated_draw: null
```

Same issue: If the field has no value, omit it from the definition. Otherwise it will fail validation.

**Comment by jemery27** [comment]
Thank you

**Pull request merged**
