### PR TITLE
Add max hauri bachmann t13 pdu

### PR DESCRIPTION
**Pull request by Napsty**
Add Max Hauri Bachmann PDU
Input: C14
Outlets: 8 x T13 (ITA Type J)

image

### CODE REVIEW

**Comment by ravench** [comment]
Consider adding the weight of the unit:
```yaml
weight: 0.96
weight_unit: 'kg
```

**Comment by ravench** [comment]
Fix indenting:
```yaml
---
manufacturer: Max Hauri
model: Bachmann 107686
slug: bachmann-107686
part_number: '107686'
u_height: 1.0
is_full_depth: false
comments: 'Rack PDU, 1U, 10A, 208/230V, (8)T13'
weight: 0.96
weight_unit: 'kg'
power-ports:
  - name: Power Port 1
    type: iec-60320-c14
    maximum_draw: 10.0
power-outlets:
  - name: Outlet 1
    type: ita-j
    power_port: Power Port 1
  - name: Outlet 2
    type: ita-j
    power_port: Power Port 1
  - name: Outlet 3
    type: ita-j
    power_port: Power Port 1
  - name: Outlet 4
    type: ita-j
    power_port: Power Port 1
  - name: Outlet 5
    type: ita-j
    power_port: Power Port 1
  - name: Outlet 6
    type: ita-j
    power_port: Power Port 1
  - name: Outlet 7
    type: ita-j
    power_port: Power Port 1
  - name: Outlet 8
    type: ita-j
    power_port: Power Port 1
```

**Comment by Napsty** [comment]
@ravench thx for the hints. do you want me to do close this one and create a new pull request? for some reason this PR also contains changes in pickle tests I never touched

**Comment by danner26** [comment]
Hey, I resolved a few problems but I need you to please fix the pickle file issues. You can try to grab the latest file or you can open a new PR which should resolve it

**Comment by Napsty** [comment]
Replaced by #2433 2433

**Pull request closed without merging**
