### PR TITLE
ubiquiti-all-unifi-devices

### PR DESCRIPTION
**Pull request by kantchev**
Added all UniFi devices from Ubiquiti (UAS, UDM, US, USG, USW)

### CODE REVIEW

**Comment by ryanmerolle** [comment]
@kantchev is that how the unifi switchports display?  IE `RJ45 1` I have a edgerouter and that is not the naming convention.

**Comment by kantchev** [comment]
> 
> 
> @kantchev is that how the unifi switchports display? IE `RJ45 1` I have a edgerouter and that is not the naming convention.

Thanks for pointing out. I will rework the port labels/names

**Comment by ryanmerolle** [comment]
@kantchev let me know when you are done and I will review again.

**Comment by tobiasehlert** [comment]
I've added PR https://github.com/netbox-community/devicetype-library/pull/178 related to UniFi devices.
Added 4 switches in my PR that are missing in this PR (didn't know how to merge them into this PR).

**Comment by DanSheps** [comment]
Did you update this PR?

**Comment by kantchev** [comment]
I updated the port labeling although there seems to be a bit of lazyness on Ubiquiti's site.. the SFP ports in the Network Controller are differently labelled as on the device itself (Controller SFP 1/2 <> just 25/26 on the device).

It would be great to have an "alias" or addition "label" field for the ports to give the port more semantic information.

.. or even an CLI definition for the port, if you one wants to automagically configure the device and/or netbox.

**Pull request merged**
