### PR TITLE
F5 big ip r4600

### PR DESCRIPTION
**Pull request by soundtech2003**
This is the addition of the F5 BigIP r4600 load balancer

### CODE REVIEW

**Comment by danner26** [comment]
Please make sure you are properly formatting the files. If you click on the files changed tab, you should see the issues annotated.

**Comment by soundtech2003** [comment]
Thank you for the info. This is my first pull request so it’s definitely a learning experience. I’ve made a ton of objects in net box I’d love to contribute, just need to figure out the process first Iassic ***@***.*** Jul 25, 2023, at 4:32 PM, Daniel W. Anner ***@***.***> wrote:﻿
Please make sure you are properly formatting the files. If you click on the files changed tab, you should see the issues annotated.

**Comment by danner26** [comment]
No worries. A few notes.
Make sure the first line of each file has `---`
Next, make sure the indentation is correct. Each indent should be 2 spaces and they should adhere to YAML formatting
Finally, make sure your file ends with a blank newline (no spaces in that newline either)

**Comment by soundtech2003** [comment]
Thank you! I'll get those notes applied to the file and have the system recheck my work.

**Comment by soundtech2003** [comment]
I'm unsure what might be wrong with the formatting on the updated file; the formatting looks identical to the i4600 the configuration is modeled after.  I've added the "---" at the beginning, the extra empty line at the end and adjusted the spacing for each line accordingly. Any advise is greatly appreciated!

**Comment by danner26** [comment]
I can assist but you have closed the PR and deleted the branch. I cannot troubleshoot this if you close the PR and delete the branch. Feel free to create a new PR, and when it fails ping me to assist with fixing it

**Pull request closed without merging**
