### PR TITLE
Updated Cisco ASR1001-X

### PR DESCRIPTION
**Pull request by abhi1693**
added missing interfaces

### CODE REVIEW

**Comment by ryanmerolle** [comment]
Is there a link to the specifications we could reference?

**Comment by ekrichbaum** [comment]
I only have 2 left on the network, so that doesn't look right. That should be from a module in a module bay.
image

https://www.cisco.com/c/en/us/products/routers/asr-1001-x-router/index.html

I do seem to remember there was a model that had different GE ports but it isn't in my brain anymore. The device type already there should probably instead get a modulebay installed for the SPA and then the SPA modeled.  Or if there is a specific different version of the box then a new model created.

**Comment by ryanmerolle** [comment]
That is what I was thinking,  The original contributor added the device without the module bay populated, which is correct.

**Comment by DanSheps** [comment]
Yup, these interfaces are modules, not fixed interface.

**Comment by abhi1693** [comment]
I'm closing since I followed the original contributor but seems like that's the wrong way to make changes.

**Pull request closed without merging**
