### PR TITLE
Added Middle-Atlantic Storage Dawers and Tripp Lite Passthrough Patch Panel

### PR DESCRIPTION
**Pull request by kbrown900**
Added a small but desired feature of the Middle Atlantic storage drawers of the 2U and 4U variants. Also added the Tripp Lite pass through 24 port patch panel (pre Cat5e).

### CODE REVIEW

**Comment by kbrown900** [comment]
Closed for further testing on why it is failing on yaml.

**Comment by kbrown900** [comment]
I can't find where the issue is at, any help appreciated.

**Review by DanSheps — APPROVED** [review]

**Comment by DanSheps** [comment]
Any chance these have weights you can assign?

**Comment by kbrown900** [comment]
> Any chance these have weights you can assign?

Not that I have been able to find unfortunately. Best I could find was shipping weight for the patch panel which won't be entirely accurate.

**Pull request merged**
