### PR TITLE
Add multiple device types (Cisco, Infoblox, Fortigate, HPE)

### PR DESCRIPTION
**Pull request by deku-m**
I made a couple of device types which we use..

### CODE REVIEW

**Comment by deku-m** [comment]
Can the "+"  be supported in naming and model/part-number/slug?

**Comment by ryanmerolle** [comment]
@deku-m I love the contribution here.  It's hard to review given all the different models you have bulked into one PR.  Would you be able to separate this out logically so I can review and approve quickly for each grouping.

**Comment by deku-m** [comment]
> 
> 
> @deku-m I love the contribution here. It's hard to review given all the different models you have bulked into one PR. Would you be able to separate this out logically so I can review and approve quickly for each grouping.

I think i need to create new branches for each new device-type then isnt it?

**Comment by deku-m** [comment]
Making a new one as per PR.

**Pull request closed without merging**
