### PR TITLE
Update MikroTik devices

### PR DESCRIPTION
**Pull request by ZoLuSs**
Update MikroTik devices that is not compliant with bulk import function by adding u_height and add is_full_depth info.

### CODE REVIEW

**Comment by danner26** [comment]
Are these devices actually half of a rack unit?? If these are not rack mountable, then they should be marked as `u_height: 0`

**Comment by ZoLuSs** [comment]
Yeah they are half rack for some of them. I change that quickly !

**Comment by ZoLuSs** [comment]
Mikrotik is really complicated for this...
For example, RB5009 can be rack mounted with RB5009 rackmount kit K-79. But the adapter can fit 4 RB5009 in 1U.
So, should I make RB5009 1U, should they be 0U since by default it's no rack mountable or should I create the rack adapter (for stacking multiple devices) with 1U as parent and device as child with 0U.

What do you think of this:
No rack adapter include: 0U
Rack adapter for stacking multiple device in 1U:  0U and I create the rack adapter as parent with 1U and device as child.
Rack adapter included or Rack mountable: 1U

**Comment by danner26** [comment]
Alright so I talked with the internal maintainers. We are in agreement the rack adapter should be created as its own 1U device marked as a parent, with 4 device bays
Then the devices should be created with `u_height: 0` and defined as child devices

**Comment by danner26** [comment]
@ZoLuSs when you complete working on this, please let me know. In the meantime I am marking this as a draft PR

**Comment by danner26** [comment]
Hello, unfortunately today we had to make a change to the schema in which weight is defined by. The upstream NetBox API requires weight to be passed to it in the following format:
```
weight: 12.01
weight_unit: lb
```

Due to this change, I have updated your branch against the current master. This might require you to update your PR, if you had weight currently defined, so that your PR is in-line with the new weight schema. If you have any issues, please let me know or refer to [this PR](https://github.com/netbox-community/devicetype-library/pull/1187) for more information.

**Comment by ZoLuSs** [comment]
Hey @danner26 can you help me ?
On my computer I run 'pre-commit run --all' but all the error are related to other file (that I don't have touch):

`Lint YAML files..........................................................Failed
- hook id: yamllint
- exit code: 1

module-types/Eaton/EMPDT1H1C2.yaml:5:47: [error] trailing spaces (trailing-spaces)
device-types/Eaton/9PXEBM180.yaml:9:28: [error] trailing spaces (trailing-spaces)
device-types/Eaton/9PX3000iRT2U.yaml:9:28: [error] trailing spaces (trailing-spaces)
device-types/ZTE/C300.yaml:9:79: [error] trailing spaces (trailing-spaces)
module-types/Eaton/Network-M2.yaml:5:31: [error] trailing spaces (trailing-spaces)
device-types/Eaton/9PXEBM72RT2U.yaml:9:28: [error] trailing spaces (trailing-spaces)
device-types/Dell/DMPU2016-G01.yml:9:31: [error] trailing spaces (trailing-spaces)
device-types/Adtran/TA-5000-23in.yaml:9:114: [error] trailing spaces (trailing-spaces)
device-types/Eaton/9PX5KIRTN.yaml:7:55: [error] trailing spaces (trailing-spaces)`

So my PR is correct but failed to pass check because of the others files. Am I wrong ?
Can this PR be merge ?

**Comment by danner26** [comment]
Hey @ZoLuSs I just pulled the master branch and ran pre-commit without issue. Are you sure you created your branch off of the latest master?

**Comment by danner26** [comment]
I believe I have fixed the issue now, sorry about that!

**Comment by danner26** [comment]
It appears to be `CCR1009-8G-1S-1S+.yaml` which is causing the error. Line 6/7 is the specific problem. Since the string is so long it wants it cut down. I fixed the issue for you

**Pull request closed without merging**
