### PR TITLE
Create PowerEdge_R750.yaml

### PR DESCRIPTION
**Pull request by bbrk364**
adding the device-bays

### CODE REVIEW

**Review by DanSheps — CHANGES_REQUESTED** [review]

**Comment by ciroiriarte** [comment]
Hello!, Any update on this?

**Comment by danner26** [comment]
@bbrk364 please fix this, there appears to be a duplicate already in the master branch

**Comment by danner26** [comment]
Also looks like this is the same as #958 
Please choose which you would like, and close the other. If neither are needed, please close both. Thanks!

**Comment by danner26** [comment]
Hello @bbrk364 
I am closing this as it has been 3 weeks without any progress. It still currently has a duplicate PR made by yourself.

If you would like to still make a contribution, please reopen this PR and fix the issue, or open a new PR on a new branch after syncing your master with the upstream.

**Pull request closed without merging**
