### PR TITLE
Check Point: Add SG23800 and add/move modules

### PR DESCRIPTION
**Pull request by konimex**
Commits should be self-explanatory.

Modules are incorrectly categorized as devices so I moved and changed the templates.

### CODE REVIEW

**Comment by konimex** [comment]
I don't think there's anything else to add as for now.

**Comment by danner26** [comment]
@konimex 
Hello, we have recently fixed a handful of formatting issues. In doing so it looks like your PR is out of sync. In order to fix this, please do the following:

1. Sync your forks master branch with the upstream
```
git fetch upstream
git checkout master
git merge upstream/master
```
2.  Checkout your branch again `git checkout BRANCH_NAME` where BRANCH_NAME is the name of your branch
3. Merge master into your branch `git merge master`
4. Fix any conflicts or issues found
5. Stage the changes `git add --all`
6. Run pre-commit scripts `pre-commit run`
7. Commit and push your changes

We are sorry for the inconvenience but it was a nessecary step. Thank you!

**Comment by konimex** [comment]
Alright. Changes made and pushed.

**Comment by danner26** [comment]
@konimex please review the build run and fix the failure cases

If you use `pre-commit run -a` you should be able to catch the failures before pushing them as well

**Comment by konimex** [comment]
Whoops, looks like my `pre-commit` command only runs the YAML lint check for some reason. Anyway, all errors should be fixed and the tests should pass now.

**Comment by danner26** [comment]
Looking good, thanks! @konimex

**Pull request merged**
