### PR TITLE
Add power type other

### PR DESCRIPTION
**Pull request by m2martin**
Add the type `other` for power ports and power outlets to validation.

### CODE REVIEW

**Comment by danner26** [comment]
Hey @m2martin you can't modify the schema files. If you want to add other types, you need to create a discussion/issue with the upstream NetBox repository. Once the type is merged into NetBox, then we can add it here. Until that is done we will not be able to merge this PR and since there are no other changes we will close this PR as well for now. You can refer to [this PR](https://github.com/netbox-community/devicetype-library/pull/1039) as a way to go about it (specifically he got the type added to the upstream, then had it added here).

If you do create an issue/PR in NetBox, please link it to an issue in this repo so we can track it as well.

**Comment by m2martin** [comment]
@danner26 this PR is especially because Netbox does have this type and `devicetype-libraray` does not.
Please see https://github.com/netbox-community/netbox/commit/e5aa9d47f740eae5cb5c56389ce0a00c06db9318

**Comment by danner26** [comment]
Thank you for linking to the PR. Schema changes we require a link to the committed change in the upstream repository
Sorry for not catching that the other day

**Comment by danner26** [comment]
It looks like the original branch was either force pushed or recreated so I cannot reopen this PR and merge it. If you would like, please recreate this PR so we can merge it. Thanks!

**Pull request closed without merging**
