### PR TITLE
Add Catalyst WS-C2960XR-24TD-I

### PR DESCRIPTION
**Pull request by squintfox**

### CODE REVIEW

**Comment by danner26** [comment]
@squintfox please add `weight` if you can find it, and also please link the datasheet in the `comments`. Thank you!

**Comment by squintfox** [comment]
@danner26 Updated as requested

**Comment by danner26** [comment]
Are the PSUs hot swappable? I don't have this exact unit in my lab so I cannot really check. If they are hot swappable they should be defined as module bays rather than PSUs themselves

**Comment by squintfox** [comment]
@danner26 Yup, you're right.  I updated it as modular.

**Pull request merged**
