### PR TITLE
Multiple templates for Cisco devices

### PR DESCRIPTION
**Pull request by jdrew82**
This PR includes multiple templates for various Cisco devices and corrections for a few to ensure consistency.

### CODE REVIEW

**Comment by ryanmerolle** [comment]
Failures:
```
/home/runner/work/devicetype-library/devicetype-library/tests/test_definitions.py:54: Failed: device-types/Cisco/WS-C4500X-32SFP++.yaml failed validation: 'ws-c4500x-32sfp++' does not match '^[-a-zA-Z0-9_]+$'
391
/home/runner/work/devicetype-library/devicetype-library/tests/test_definitions.py:54: Failed: device-types/Cisco/WS-C4510R+E.yaml failed validation: 'ws-c4510r+e' does not match '^[-a-zA-Z0-9_]+$'
392
/home/runner/work/devicetype-library/devicetype-library/tests/test_definitions.py:54: Failed: device-types/Cisco/WS-C4500X-16SFP++.yaml failed validation: 'ws-c4500x-16sfp++' does not match '^[-a-zA-Z0-9_]+$'
393
/home/runner/work/devicetype-library/devicetype-library/tests/test_definitions.py:54: Failed: device-types/Cisco/WS-C4507R+E.yaml failed validation: 'ws-c4507r+e' does not match '^[-a-zA-Z0-9_]+$'
```

**Comment by jdrew82** [comment]
I had seen those but was unclear of how to handle since it appears that your regex isn't accounting for a + symbol. I've confirmed that it is a standard symbol used in Cisco's device models so would it be possible to allow for that character? I believe an update to ^[-a-zA-Z0-9_+]+$ should be sufficient.

**Comment by jdrew82** [comment]
Saw that this is an API limitation due to it being URL so I've fixed the templates to take that into account. Passing pytest now.

**Comment by jdrew82** [comment]
Hey @ryanmerolle, can you re-eval this and approve it?

**Pull request merged**
