### PR TITLE
Add Palo Alto ION 5200

### PR DESCRIPTION
**Pull request by collin-clark**
Create Palo Alto ION 5200 device type

### CODE REVIEW

**Comment by danner26** [comment]
Hello, the pickle files should never be committed. Please remove them from the PR so we can evaluate this further

**Review by collin-clark — COMMENTED** [review]
file clean up

**Comment by danner26** [comment]
Hello, you still have an issue with the pickle files and now the gitignore too. Please correct this so we can review.

**Comment by danner26** [comment]
Closing this since it has been incomplete for a long period of time. Feel free to work on it then reopen it again if you would like.

**Pull request closed without merging**
