### PR TITLE
Adding the UniFi Dream Machine (non-pro)

### PR DESCRIPTION
**Pull request by sawasy**

### CODE REVIEW

**Comment by danner26** [comment]
Hey @sawasy, looks like your airflow definition is incorrect. The valid values are: `'front-to-rear', 'rear-to-front', 'left-to-right', 'right-to-left', 'side-to-rear', 'passive'`

If you update the PR, we can review further. Thanks!

**Comment by sawasy** [comment]
Whoops! Thanks @danner26 . I've updated the device as passive. It has active airflow, but it's bottom to top. Seems like the best option.

m!

**Comment by danner26** [comment]
@sawasy correct me if I am wrong, but on my UDMP the ports are listed as Port 1, Port 2, etc. Is this different on the UDM? If not, we should change the names to match the `Port #` format and use the label for the printed usage such as `LAN` or `WAN`

**Comment by danner26** [comment]
Also please make sure the power type is one of the following:

`'iec-60320-c6', 'iec-60320-c8', 'iec-60320-c14', 'iec-60320-c16', 'iec-60320-c20', 'iec-60320-c22', 'iec-60309-p-n-e-4h', 'iec-60309-p-n-e-6h', 'iec-60309-p-n-e-9h', 'iec-60309-2p-e-4h', 'iec-60309-2p-e-6h', 'iec-60309-2p-e-9h', 'iec-60309-3p-e-4h', 'iec-60309-3p-e-6h', 'iec-60309-3p-e-9h', 'iec-60309-3p-n-e-4h', 'iec-60309-3p-n-e-6h', 'iec-60309-3p-n-e-9h', 'nema-1-15p', 'nema-5-15p', 'nema-5-20p', 'nema-5-30p', 'nema-5-50p', 'nema-6-15p', 'nema-6-20p', 'nema-6-30p', 'nema-6-50p', 'nema-10-30p', 'nema-10-50p', 'nema-14-20p', 'nema-14-30p', 'nema-14-50p', 'nema-14-60p', 'nema-15-15p', 'nema-15-20p', 'nema-15-30p', 'nema-15-50p', 'nema-15-60p', 'nema-l1-15p', 'nema-l5-15p', 'nema-l5-20p', 'nema-l5-30p', 'nema-l5-50p', 'nema-l6-15p', 'nema-l6-20p', 'nema-l6-30p', 'nema-l6-50p', 'nema-l10-30p', 'nema-l14-20p', 'nema-l14-30p', 'nema-l14-50p', 'nema-l14-60p', 'nema-l15-20p', 'nema-l15-30p', 'nema-l15-50p', 'nema-l15-60p', 'nema-l21-20p', 'nema-l21-30p', 'nema-l22-30p', 'cs6361c', 'cs6365c', 'cs8165c', 'cs8265c', 'cs8365c', 'cs8465c', 'ita-c', 'ita-e', 'ita-f', 'ita-ef', 'ita-g', 'ita-h', 'ita-i', 'ita-j', 'ita-k', 'ita-l', 'ita-m', 'ita-n', 'ita-o', 'usb-a', 'usb-b', 'usb-c', 'usb-mini-a', 'usb-mini-b', 'usb-micro-a', 'usb-micro-b', 'usb-micro-ab', 'usb-3-b', 'usb-3-micro-b', 'dc-terminal', 'saf-d-grid', 'hardwired'`

**Comment by danner26** [comment]
Also please update the power type of Other, since we do not have c5 as an option currently

**Comment by sawasy** [comment]
Updated the power supply to 'other'. I am not sure what you mean with regard to the port labels. From what I can see they are the same as the UDMP.  Am I missing something?

Cheers

m!

**Comment by danner26** [comment]
Thanks for updating power
As for the port names, in the UI config they are called Port 1, Port 2, Port 3, etc. Rather than naming the ports eth0, eth1, etc we should have them named the same as the configuration does. Let me know if that makes more sense @sawasy

**Comment by sawasy** [comment]
Sure, @danner26, we can change the name to the "Port x".  I was following the yaml file layout for the UDM-Pro.  It has Port 1-11 in the GUI, but uses eth0-10 for the name.  Would you like me to update the UDM-Pro as well? No problem updating both.


Cheers

m!

**Comment by danner26** [comment]
Okay so I just verified in UnifiOS each port is listed as port.<number> i.e. port.1, port.2, etc
So lets go with Port 1, Port 2, etc
If youd like to update the UDMP I am fine with that as well

**Review by danner26 — APPROVED** [review]

**Comment by danner26** [comment]
@sawasy I am sorry, I messed that up. I must have been confused earlier because there is no power type other. In fact, according to https://community.fs.com/blog/small-power-cord-big-difference.html the type that the UDM uses on the appliance side is a `iec-60320-c8`
Please update it to reflect that.. Sorry again!

**Comment by sawasy** [comment]
I see that 'other' isn't valid. No good alternatives, so I'll just go with 'iec-60320-c6'.

m!

**Comment by danner26** [comment]
> I see that 'other' isn't valid. No good alternatives, so I'll just go with 'iec-60320-c6'. Edit: Ok. iec-60320-c8 it is. One moment.
> 
> m!

Glad you saw my update! Appreciate it. C6 has an earth ground, whereas the UDM does not (2 prong only, so it is a C8)

**Comment by sawasy** [comment]
:tada: It was an adventure, but we got there. Thanks!

m!

**Comment by danner26** [comment]
@sawasy Absolutely! Glad we made it and I look forward to your next PR. Have a great rest of the year

**Pull request merged**
