### PR TITLE
Create UCS-X9508.yaml

### PR DESCRIPTION
**Pull request by deku-m**

### CODE REVIEW

**Comment by danner26** [comment]
Hey @deku-m please resolve the formatting and test issues, then feel free to mark this PR as ready for review again

**Comment by deku-m** [comment]
> Hey @deku-m please resolve the formatting and test issues, then feel free to mark this PR as ready for review again

Hi @danner26 
How to handle this when its a device-bay and power is in the module-bay?
As the error comes from is_powered device right?

**Comment by danner26** [comment]
Please review the errors and correct them, thanks

**Comment by deku-m** [comment]
> Please review the errors and correct them, thanks

What is the mistake i am making? Can you point me to that

**Comment by danner26** [comment]
Utilizing `pre-commit run -a` on your branch, with the already committed changes I was able to find the following. The formatting step corrected `weight_unit: 'kg'` to `weight_unit: kg`

**Comment by danner26** [comment]
`pre-commit` is a powerful tool that will assist you greatly once you learn to use it

**Review by danner26 — APPROVED** [review]

**Pull request merged**
