### PR TITLE
adding HP t740 thin client (used as router)

### PR DESCRIPTION
**Pull request by SimonFischer04**
Adding device-type for the HP t740 thin client (used as a router by me).

Inspired by: https://github.com/netbox-community/devicetype-library/blob/master/device-types/Intel/NUC11TNHi5.yaml

### CODE REVIEW

**Comment by danner26** [comment]
Hello, the manufacturer should be HPE. Please follow standards already defined in this repository. You can refer to the HPE folder if you want to see some examples but be wary because some of the files might be slighly outdated from current available data points.

**Comment by SimonFischer04** [comment]
I put them into HP intentionally, infact because
I actually looked at the hp example before and did some research.

Sorry if I don't understand this correctly / overlooked something, but:
Looking at this again for example (just a random recently updated one): 
https://github.com/netbox-community/devicetype-library/blob/master/device-types/HPE/HP-3100-24-v2-EI.yaml 
while the file is called "hp-..." the linked support page spec clearly states it as an **HPE** device.
**HP** and **HPE** are two different companies and this **t740 is a HP** device, so I thought I had to create another folder.

But as requested, changed it now anyways.

**Comment by danner26** [comment]
Hello, so a lot of those devices are pre-exisitng before we migrated them to a new schema. 

HPE (Hewlett Packard Enterprise) is the manufacturer, if the device is branded HP instead of HPE that is fine. In that case the device can be called `HP-whatever` but the manufacturer remains HPE as they are the parent comanpy that manufactures and owns the device. The idea is to reduce the number of manufacturers, like Cisco and Meraki. That is the thought process at least.

Let me know if this PR is ready to be reviewed

**Comment by SimonFischer04** [comment]
> The idea is to reduce the number of manufacturers, like Cisco and Meraki. That is the thought process at least.
Oh, not having tons of manufacturers makes sense, thanks for explaining

> Let me know if this PR is ready to be reviewed
Yes, then it's ready from my side.

**Pull request merged**
