### PR TITLE
HPE Apollo Chassis with Blade/Sled Servers and module

### PR DESCRIPTION
**Pull request by adamboutcher**
This is to include the R2000 Series sled/blade chassis and the xl170 nodes. There is an RCM module specifically for this chassis too.

### CODE REVIEW

**Comment by danner26** [comment]
Please resolve all test cases before marking this PR ready

**Comment by adamboutcher** [comment]
What's failed?

**Comment by danner26** [comment]
@adamboutcher the formatting check failed, you can run `pre-commit run -a` which will give you the full output of what is wrong.

**Comment by adamboutcher** [comment]
It was initially missing some indentation so I added it but the second run I couldn't see the actual error output.

**Comment by danner26** [comment]
If you run `pre-commit run -a` as defined in the readme you will see the formatting and errors. The first issue is that the file names are incorrect, the file name should match the model or part number. Please adjust the file names accordingly

Also, 2 of your files do not have file extensions.

**Review by harryajc — APPROVED** [review]

**Pull request merged**
