### PR TITLE
Arista DCS-7368 got two Management interfaces

### PR DESCRIPTION
**Pull request by c-po**

### CODE REVIEW

**Comment by ryanmerolle** [comment]
Technically its the supervisor module that has them.  Would you want to introduce the proper modules now that NetBox 3.2 supports modeling modules?

**Comment by c-po** [comment]
@ryanmerolle sure will do.

Is there also planned support to define the line-card power consumption?

From https://www.arista.com/assets/data/pdf/Datasheets/7368X4-Datasheet.pdf


image

**Comment by ryanmerolle** [comment]
That is not a feature currently requested by the user community.

**Comment by ryanmerolle** [comment]
- netbox-community/netbox#9246

**Comment by c-po** [comment]
Extended the chassis with position for the slot IDs.

image

This resolves the wrongly opened issue https://github.com/netbox-community/netbox/issues/9246

**Pull request merged**
