### PR TITLE
Added Canon manufacturer and some iR-ADV C3xxx devices

### PR DESCRIPTION
**Pull request by vittore**

### CODE REVIEW

**Comment by vittore** [comment]
Please add

**Comment by danner26** [comment]
Hey @vittore, please add a newline to the end of your file so it passes validation. Tag me once you update the PR so I can re-review! Thanks

Also, as a tip for the future, if you use pre-commit as described in the readme, it will fix these issues for you. If you have any questions feel free to let me know

**Comment by vittore** [comment]
Thanks for suggesting. Done.

**Comment by danner26** [comment]
@vittore one last thing for this one, are these rack mountable? If so, please put the `u_height`, if not, please set 'u_height: 0`

**Comment by vittore** [comment]
Set u_height to zero.

Il giorno mar 27 dic 2022 alle ore 19:37 Daniel Anner <
***@***.***> ha scritto:

**Comment by danner26** [comment]
Looking good! I will go ahead and merge this

**Comment by danner26** [comment]
Before I merge this, can you add the power as well? @vittore

**Comment by danner26** [comment]
@vittore I have updated your files to include the product sheet as well as, commented out, power ports. Please fill them in when you get a chance. I tried to find what type of adapter they use, but I could not find a picture or anything.

**Comment by danner26** [comment]
Hello @vittore , are you able to work on this?

**Comment by vittore** [comment]
Yes, I can, this night.

v.


Il giorno lun 9 gen 2023 alle ore 17:58 Daniel W. Anner <
***@***.***> ha scritto:

**Review by vittore — COMMENTED** [review]
Add power port iec-60320-c14

**Comment by danner26** [comment]
Much appreciated!

**Pull request merged**
