### PR TITLE
Rename Rohde und Schwarz folder

### PR DESCRIPTION
**Pull request by FloEisen**
Renamed the "Rohde und Schwarz" vendor folder in order to avoid errors due to whitespaces

### CODE REVIEW

**Comment by ryanmerolle** [comment]
What white space errors?  If there are some, why not surround the value in quotes?

**Comment by FloEisen** [comment]
For example with the Python import script, where whitespaces are used as delimiter between vendors within the "vendors" env-variable. Quotes didn't work for me here.

I know, it would be cleaner to change the script to use other delimiter.
But another reason is to get rid of the "und" as it is a German word and not the best for the international name of Rohde & Schwarz.

**Comment by ryanmerolle** [comment]
The only issue is that the device will now show up in netbox associated to a manufacturer name that will look odd with no space when there should be.  How about we quote it with the & and spaces?

**Comment by FloEisen** [comment]
Yes, good point! I tested it successfully with the &. Commited the changes
Thanks!

**Pull request merged**
