### PR TITLE
Arista 7050X4 Family

### PR DESCRIPTION
**Pull request by suom1**
- Two new 100G SFP types (DSFP and SFP-DD)
- 7 New switches

PSU's used for these Switches are found in #1475

### CODE REVIEW

**Comment by danner26** [comment]
Are the `100gbase-x-sfpdd` actually suppose to be `100gbase-x-qsfpdd`?

**Comment by danner26** [comment]
I have created a [PR ](https://github.com/netbox-community/netbox/pull/13236)for dspf 100G adapter. Please let me know your thoughts about the sfpdd/qsfpdd interface

**Comment by suom1** [comment]
> Are the `100gbase-x-sfpdd` actually suppose to be `100gbase-x-qsfpdd`?

SFP-DD is in regular SFP size and not QSFP size, that's why we need to add it :) Different form factor.

**Comment by danner26** [comment]
Hello, I have updated the PR to inslude both new types. Once that is merged we can proceed with this.

**Comment by danner26** [comment]
Hey @suom1 please fix the slug issue

**Comment by danner26** [comment]
Also please remove your changes/make them match what we have commited into master. Thanks!

**Comment by suom1** [comment]
@danner26 ready for review now! :)

**Review by danner26 — APPROVED** [review]

**Pull request merged**
