### PR TITLE
Addition of Ubiquiti Switch Pro Aggregation

### PR DESCRIPTION
**Pull request by reishoku**
This PR introduces Ubiquiti Switch Pro Aggregation and `ubiquiti-smartpower` Power Connector.

Datasheet (Direct Link, PDF): https://dl.ui.com/ds/usw-pro-aggregation_ds.pdf

Related Issue in netbox-community/netbox:
- https://github.com/netbox-community/netbox/issues/9192
- https://github.com/netbox-community/netbox/issues/9343

-----
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~@~ pm.me>

### CODE REVIEW

**Comment by danner26** [comment]
@reishoku Unfortunately, you cannot modify the schema files. These have to reflect the upstream netbox repo interface types. If you would like to add a new type, you need to create a request in the upstream netbox repo first. Once merged there, then we can support it in this repo

That being said the USP-RPS provides DC port, and is effectively a proprietary DC terminal connection. In this case, the power port type should be `dc-terminal`.

You are of course welcome to chat with the upstream netbox maintainers, and if they decide to add a specific type for the USP, then we can support it here. I do not think they will since like I said, it is a DC terminal. I have already reverted the changes to components.json and set the USP-RPS port to `dc-terminal`. Please review my changes and let me know if they are ready to be merged.

**Comment by danner26** [comment]
I totally misread the description and that it was already requested and merged. Please go ahead and revert my changes. 

I am sorry about that!

**Comment by danner26** [comment]
Thanks @reishoku sorry again about that

**Comment by reishoku** [comment]
Thank you for your advice and I'm sorry!
I realized that I should be more careful about the description of this PR.

Just reverted changes (I'm relatively new to git, so if this is not what was supposed to do, please let me know).

**Comment by danner26** [comment]
You did exactly what I didn't have access to. It is late here, I just misread unfortunately

**Pull request merged**
