### PR TITLE
Digi PortServer TS 8/16

### PR DESCRIPTION
**Pull request by ravench**

### CODE REVIEW

**Comment by ravench** [comment]
I can't figure out why the test doesn't pass, as this file exists:
```shell
> file elevation-images/Digi/digi-ts-16.jpg
elevation-images/Digi/digi-ts-16.jpg: JPEG image data,...
```

**Comment by ravench** [comment]
I can't figure out why the test doesn't pass, as this file exists:
```shell
$ file elevation-images/Digi/digi-portserver-ts-16.jpg
elevation-images/Digi/digi-portserver-ts-16.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=GIMP 2.10.38, datetime=2024:11:13 14:14:17], progressive, precision 8, 847x78, components 3
```

**Comment by harryajc** [comment]
> I can't figure out why the test doesn't pass, as this file exists:
> 
> ```shell
> $ file elevation-images/Digi/digi-portserver-ts-16.jpg
> elevation-images/Digi/digi-portserver-ts-16.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=GIMP 2.10.38, datetime=2024:11:13 14:14:17], progressive, precision 8, 847x78, components 3
> ```

Its because the image file name is missing the .front. It should be digi-portserver-ts-16.front.jpg

**Comment by ravench** [comment]
> Its because the image file name is missing the .front. It should be digi-portserver-ts-16.front.jpg

Thanks. I was to focused on the error message to notice.

**Review by harryajc — APPROVED** [review]

**Pull request merged**
