### PR TITLE
Add Cisco N540-28Z4C-SYS-D

### PR DESCRIPTION
**Pull request by deesel**

### CODE REVIEW

**Comment by danner26** [comment]
Hey @deesel, I have not worked with an N540, so I just want to verify that the interface labelling `TenGigE0/0/0/13` is correct. If you could show us an output from the console that would be highly appreciated. Thanks!

**Comment by danner26** [comment]
Also, per the contribution guide, we request that you use the complete interface name. See below for a snippet from the contributing guide
`Use the complete form of interface names where applicable. For example, use TenGigabitEthernet1/2/3 instead of Te1/2/3.`

**Comment by deesel** [comment]
Yes, labelling is correct. I also understand the requirement to use complete interface names. However `show interfaces` command (output of which includes full interface names for most platforms) shows names that seem to be abbreviated:

```
RP/0/RP0/CPU0:n540-28z4c-sys-d#sh ver | i N540
cisco N540-28Z4C-SYS-D (C3708 @ 1.70GHz) processor with 8GB of memory

RP/0/RP0/CPU0:n540-28z4c-sys-d#sh interfaces | i line protocol
MgmtEth0/RP0/CPU0/0 is administratively down, line protocol is administratively down
HundredGigE0/0/0/28 is up, line protocol is up
HundredGigE0/0/0/29 is administratively down, line protocol is administratively down
HundredGigE0/0/0/30 is administratively down, line protocol is administratively down
HundredGigE0/0/0/31 is administratively down, line protocol is administratively down
TenGigE0/0/0/0 is up, line protocol is up
TenGigE0/0/0/1 is up, line protocol is up
TenGigE0/0/0/2 is up, line protocol is up
TenGigE0/0/0/3 is administratively down, line protocol is administratively down
TenGigE0/0/0/4 is administratively down, line protocol is administratively down
TenGigE0/0/0/5 is administratively down, line protocol is administratively down
TenGigE0/0/0/6 is administratively down, line protocol is administratively down
TenGigE0/0/0/7 is administratively down, line protocol is administratively down
TenGigE0/0/0/8 is administratively down, line protocol is administratively down
TenGigE0/0/0/9 is administratively down, line protocol is administratively down
TenGigE0/0/0/10 is administratively down, line protocol is administratively down
TenGigE0/0/0/11 is administratively down, line protocol is administratively down
TenGigE0/0/0/12 is up, line protocol is up
TenGigE0/0/0/13 is up, line protocol is up
TenGigE0/0/0/14 is up, line protocol is up
TenGigE0/0/0/15 is administratively down, line protocol is administratively down
TenGigE0/0/0/16 is administratively down, line protocol is administratively down
TenGigE0/0/0/17 is administratively down, line protocol is administratively down
TenGigE0/0/0/18 is administratively down, line protocol is administratively down
TenGigE0/0/0/19 is administratively down, line protocol is administratively down
TenGigE0/0/0/20 is administratively down, line protocol is administratively down
TenGigE0/0/0/21 is administratively down, line protocol is administratively down
TenGigE0/0/0/22 is administratively down, line protocol is administratively down
TenGigE0/0/0/23 is administratively down, line protocol is administratively down
TenGigE0/0/0/24 is administratively down, line protocol is administratively down
TenGigE0/0/0/25 is administratively down, line protocol is administratively down
TenGigE0/0/0/26 is administratively down, line protocol is administratively down
TenGigE0/0/0/27 is administratively down, line protocol is administratively down
```

For the sake of completeness - this apparently abbreviated interface name format is also used in configuration.

**Comment by danner26** [comment]
Very interesting, I was expecting it to show the full name like I am used to. In this case I would tend to agree with you that we should use the abbreviated name since that is what is used in the config.

I dont think this is my decision to make though, so I am tagging @jeremystretch to provide his thoughts

**Comment by jeremystretch** [comment]
Best practice is to assume whatever format is treated as canonical for the device. Since the device is listing interfaces as e.g. `HundredGigE`, let's stick with that.

**Pull request merged**
