### PR TITLE
Added RB5009UG+S+IN

### PR DESCRIPTION
**Pull request by Wlanfr3ak**
Added Device Type with Details

### CODE REVIEW

**Comment by danner26** [comment]
@Wlanfr3ak Please fix the POE type, it is not one of the types available at the moment. These are the types available
```
['type1-ieee802.3af',
              'type2-ieee802.3at',
              'type3-ieee802.3bt',
              'type4-ieee802.3bt',
              'passive-24v-2pair',
              'passive-24v-4pair',
              'passive-48v-2pair',
              'passive-48v-4pair'],
```

**Review by Wlanfr3ak — COMMENTED** [review]
Fixed Typos around PoE

**Comment by danner26** [comment]
Please set `u_height`, `is_full_depth`, and `airflow` as applicable

**Comment by Wlanfr3ak** [comment]
Device is without Rack Mount so no of the 3 values is used (passive cooling)

**Comment by danner26** [comment]
Then `u_height` should be set to `0` as it defaults to 1
`is_full_depth` should be set to `false` as it defaults to true
`airflow` should be set to `passive`

**Review by Wlanfr3ak — COMMENTED** [review]
Added more Details as wished

**Pull request merged**
