### PR TITLE
Adding SNR S2995G-24FX switch model

### PR DESCRIPTION
**Pull request by krasotinpa**

### CODE REVIEW

**Comment by harryajc** [comment]
Hi @krasotinpa Thank you for your contribution.

Please fix the conflicting files before marking this PR ready.

**Comment by krasotinpa** [comment]
Hi @harryajc - 

Could you please tell me what I should do?
I only committed one file - `S2995G-24FX.yaml`. Files `tests/known-modules.pickle` and `tests/known-slugs.pickle` were not generated by me.
How can I fix this?

Thank you in advance

**Comment by harryajc** [comment]
Hi @krasotinpa 
Not sure why it keeps re-generating the slug but it seems to be causing issues when I try to merge. Might be worth closing this PR and creating a new PR and see if it will let me merge it then.

**Comment by krasotinpa** [comment]
Ok. Let's do it

**Pull request closed without merging**
