### PR TITLE
Cisco PoE support

### PR DESCRIPTION
**Pull request by michaelklose**
Set PoE capabilities on switch interfaces

### CODE REVIEW

**Comment by danner26** [comment]
Hey @michaelklose this is a ton of changes. Generally we brake these into multiple pull requests to make reviewing easier. We also generally create these yaml files with the defaults in mind. If some of these do not have your changes by default, please revert those.

I will do my best to review all of these but it is going to take some time

**Comment by michaelklose** [comment]
Sorry for that. I can give you a bit more details about this PR.
- In general I have added PoE information to all downlink ports of the  switches which support PoE. Based on datasheets I have set Type 1, 2 or 3
- Only a view small devices support PoE PD mode on the uplink ports e.g. WS-C2960CPD-8PT.yaml
- C9300-24U.yaml was created completely new based on the C9300-48U model
-  ME-3600X-24TS-M.yaml: Removed "Cisco" from model
- C9200L-48P-4G.yaml: Corrected uplink ports to SFP
- WS-C3560X-48PF-S.yaml: Corrected ports from FastEthernet to GigabitEthernet

If there is anything else where I can help you please let me know.

Best Regards
Michael Klose

**Comment by danner26** [comment]
I appreciate the information you provided. In addition, I will take this opportunity to clean up some of the files as well as to begin adding airflow and other definitions to the files if they are not already included. Due to the large number of changes this will take some time, but I will contact you once I have completed

**Comment by danner26** [comment]
Hey @michaelklose instead of me going through these one by one using the web ui, do you think you could invite me to your forked repo? If so then I can edit them all at once and make a handful of commits rather than one for each file.

**Comment by michaelklose** [comment]
You should have an invite

**Comment by danner26** [comment]
Hey @michaelklose I just want to verify, all of these switches, do they have POE enabled by default on the switch? If so, then great. Otherwise we generally describe each devices defaults, and then the user can modify it within NetBox if they enable something else.. that being said, if POE is enabled on the port by default when you first boot the switch, then we can leave the changes.

**Comment by michaelklose** [comment]
As far as I know PoE is on per default for all Cisco switches. Please find below some references for that.

2960-X (https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst2960x/software/15-0_2_EX/int_hw_components/configuration_guide/b_int_152ex_2960-x_cg/b_int_152ex_2960-x_cg_chapter_0111.html)
auto—Enables powered-device detection. If enough power is available, automatically allocates power to the PoE port after device detection. This is the default setting. 

3850 (https://www.cisco.com/en/US/docs/switches/lan/catalyst3850/software/release/3.2_0_se/multibook/configuration_guide/b_consolidated_config_guide_3850_chapter_011010.html#con_1415439) 
auto—Enables powered-device detection. If enough power is available, automatically allocates power to the PoE port after device detection. This is the default setting. 

9300 (https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/software/release/16-12/configuration_guide/int_hw/b_1612_int_and_hw_9300_cg/configuring_poe.html)
auto : Enables powered-device detection. If enough power is available, automatically allocates power to the PoE port after device detection. This is the default setting.

**Comment by danner26** [comment]
Great @michaelklose I have reviewed 243 / 261 files so I should have this merged today. Thanks for all of your work!

**Review by danner26 — APPROVED** [review]

**Pull request merged**
