### PR TITLE
Add AP7953 / 885-0928 zero U switched rack PDU

### PR DESCRIPTION
**Pull request by FlorianHeigl**
older model, zero U, info is at https://www.apc.com/shop/ro/en/products/Rack-PDU-Switched-Zero-U-32A-230V-21-C13-3-C19/P-AP7953

### CODE REVIEW

**Comment by FlorianHeigl** [comment]
i now understood what's wrong in this PR, will try to fix it next week.

**Comment by jeremystretch** [comment]
Hi @FlorianHeigl, looks like the YAML linter is failing due to some trailing whitespace.

**Comment by danner26** [comment]
Do you still need this? @FlorianHeigl

**Comment by FlorianHeigl** [comment]
@danner26 Technically yes, but the issues I had getting it right for the CI had completely thrown me off track. 
I've given up on all submissions I had prepared.
Do you know a way how I can fully fully run the tests locally before I need to go through this process again, and so it can actually work?

**Comment by danner26** [comment]
Yes, you can use `pre-commit` to run the tests
We have instructions in the main readme on how to utilize this functionality. If you update your branch against our master, you run just run `pre-commit run -a` and it will check all of the files before commiting them

**Pull request closed without merging**
