### PR TITLE
Added RB5009UPr+S+IN

### PR DESCRIPTION
**Pull request by Wlanfr3ak**
New Type with all Details

### CODE REVIEW

**Review by Wlanfr3ak — COMMENTED** [review]
Fixed Typo

**Review by Wlanfr3ak — COMMENTED** [review]
Fixed Typos around PoE

**Comment by danner26** [comment]
Please set `u_height`, `is_full_depth`, and `airflow` as applicable

**Comment by Wlanfr3ak** [comment]
Device is without Rack Mount so no of the 3 values is used (passive cooling)

**Comment by danner26** [comment]
Then `u_height` should be set to `0` as it defaults to 1
`is_full_depth` should be set to `false` as it defaults to true
`airflow` should be set to `passive`

**Review by Wlanfr3ak — COMMENTED** [review]
Added more Details as wished

**Pull request merged**
