### PR TITLE
add synology e10m20-t1.yaml

### PR DESCRIPTION
**Pull request by jaredgrove**
Add Synology E10M20-T1

### CODE REVIEW

**Comment by danner26** [comment]
I do not believe so, but the checks will verify that. Please move it and commit that change and then I will review it further. Thanks!

**Comment by jaredgrove** [comment]
Forgive me if I'm missing something obvious, but my commit is already placing the .yaml file in module-types/Synology/E10M20-T1.yaml , isn't it?

**Comment by danner26** [comment]
@jaredgrove you are 100% correct. I am sorry, it was a long day yesterday that I clearly have not recovered from
All is good with this commit. Thank you and I will merge it soon

**Comment by jaredgrove** [comment]
@danner26 No worries at all! I'm exhausted too! Let's both get some rest today.

**Pull request merged**
