### PR TITLE
Updating Mikrotik RB960PGS Device Type with more Details

### PR DESCRIPTION
**Pull request by Wlanfr3ak**
Added PoE in/out specs, powerport, datasheet link.

### CODE REVIEW

**Review by Wlanfr3ak — COMMENTED** [review]
fixed typo

**Comment by danner26** [comment]
@Wlanfr3ak Please update this title and description to better describe what you are adding/modifying

**Review by Wlanfr3ak — COMMENTED** [review]
fixed typo, again

**Comment by danner26** [comment]
Please set `u_height`, `is_full_depth`, and `airflow` as applicable

**Review by Wlanfr3ak — COMMENTED** [review]
fixed typos

**Comment by Wlanfr3ak** [comment]
Device is without Rack Mount so no of the 3 values is used (passive cooling)

**Comment by danner26** [comment]
Then `u_height` should be set to `0` as it defaults to 1
`is_full_depth` should be set to `false` as it defaults to true
`airflow` should be set to `passive`

**Review by Wlanfr3ak — COMMENTED** [review]
Added more Details as wished

**Pull request merged**
