### PR TITLE
add Aruba ec 10104

### PR DESCRIPTION
**Pull request by SirHardware**

### CODE REVIEW

**Comment by SirHardware** [comment]
Hi, 
can someone please Assist me why the format check fails?
The error "Error: Process completed with exit code 1." isn't realy helpfull.

**Comment by danner26** [comment]
Please correct the formatting issues and then after all checks pass, mark the PR as ready for review. Thanks!

**Comment by SirHardware** [comment]
> Please correct the formatting issues and then after all checks pass, mark the PR as ready for review. Thanks!

I'd love to, but as I said the error "Error: Process completed with exit code 1." isn't realy helpfull.
If you could tell me whats wrong with the formating I will correct it.

**Comment by SirHardware** [comment]
image
So if I run yamlfmt localy with the same conf it doesn't report any errors

**Comment by danner26** [comment]
Using `pre-commit` as defined in the documentation fixed the issue. Running `pre-commit` allows you to run the tests and fix issues before they even get to GitHub. I have fixed the issue for you, and added the weight data point as well

**Review by danner26 — APPROVED** [review]

**Pull request merged**
