### PR TITLE
modules JH180A and JH181A

### PR DESCRIPTION
**Pull request by francesco-noc**
Added two HPE modules:

- (JH180A) HPE 5930 24-port SFP+ and 2-port QSFP+ Module
- (JH181A) HPE 5930 24-port SFP+ and 2-port QSFP+ with MACsec Module

### CODE REVIEW

**Comment by francesco-noc** [comment]
I'm not able to understand why it fails

**Comment by arcticash** [comment]
Hi Francesco, 
I'm not associated with this project but I've just had a quick look at your commits and I think its the interface names being in quotes which is causing the tests to fail.
If you can get the pre-commit function to run locally this will check and try to correct any issues before committing, but I think if you remove the single quotes around the interface names then this should pass the automated checks.

**Comment by Madrov** [comment]
I just fixed my PR by running the "pre-commit run --all" command on my PR #1260 and indeed that works, I tested on your files and the pre-commit removed the quote on the interface like @arcticash said. 

For example:
  - name: Ten-GigabitEthernet1/{module}/1 
instead of
  - name: 'Ten-GigabitEthernet1/{module}/1'

Somehow I could not run my venv on windows (Run PyTest case Checks step never end..). Everything is fine on ubuntu desktop... odd.

**Comment by danner26** [comment]
Thanks for jumping in and assisting @arcticash 
@francesco-noc I was away last week but I am moving through the PRs again now

**Pull request merged**
