### PR TITLE
add juniper-acx7024 images elevation

### PR DESCRIPTION
**Pull request by antoinevicot**

### CODE REVIEW

**Review by danner26 — CHANGES_REQUESTED** [review]
You will need to update the definition file associated with this device. you will need to add `front_image: true` and `rear_image: true`

**Comment by danner26** [comment]
For some reason I cannot update this branch, please update your branch against the master

**Review by antoinevicot — COMMENTED** [review]
viewed

**Comment by danner26** [comment]
I still do not see that you added the `front_image: true` and `rear_image: true` to the devices definition file. Please do so, then mark this PR as ready for review

**Comment by antoinevicot** [comment]
i have an error when I push :
`front_image: true
rear_image: true`


`============================= test session starts ==============================
platform darwin -- Python 3.12.1, pytest-8.1.1, pluggy-1.4.0 -- /Users/avicot/dev_stash/devicetype-library/.venv/bin/python3.12
cachedir: .pytest_cache
rootdir: /Users/avicot/dev_stash/devicetype-library
collected 2 items                                                              

tests/definitions_test.py::test_environment SKIPPED (No changes to d...) [ 50%]
tests/definitions_test.py::test_definitions[device-types/Juniper/ACX7024-AC.yaml-schema0-M] FAILED [100%]

=================================== FAILURES ===================================
_______ test_definitions[device-types/Juniper/ACX7024-AC.yaml-schema0-M] _______
device-types/Juniper/ACX7024-AC.yaml has Front or Rear Image set to True but no images found for manufacturer/device (slug=juniper-acx7024-ac)
=========================== short test summary info ============================
FAILED tests/definitions_test.py::test_definitions[device-types/Juniper/ACX7024-AC.yaml-schema0-M] - Failed: device-types/Juniper/ACX7024-AC.yaml has Front or Rear Image set to...
======================== 1 failed, 1 skipped in 24.24s =========================`

**Comment by antoinevicot** [comment]
done thx for your help

**Comment by danner26** [comment]
Sorry one more issue

**Review by antoinevicot — COMMENTED** [review]
done

**Review by danner26 — APPROVED** [review]

**Pull request merged**
