### PR TITLE
Add device-type RB962UiGS-5HacT2HnT

### PR DESCRIPTION
**Pull request by carlosportillo**
Device type for MikroTik RB962UiGS-5HacT2HnT added to the respository

### CODE REVIEW

**Comment by dmcken** [comment]
Hi,

The yamllint is failing on line 4:

"slug: rb962uigs-5hact2hnt "

has a trailing whitespace character.

**Comment by danner26** [comment]
Do you still need this? @carlosportillo

**Comment by carlosportillo** [comment]
Hello @danner26 , yes I do.

**Comment by danner26** [comment]
If you still want to contribute we would be happy to review it again. The original maintainers are busy but I am here to make sure the PRs get worked on
If you would like to contribute please feel free to reopen this PR, update your branch against our master, and then fix any issues. From there I will review it

**Pull request closed without merging**
