### PR TITLE
Updates and adds for Meraki, APC and Fortinet

### PR DESCRIPTION
**Pull request by squintfox**
This includes corrections for Fortinet and Meraki items as well as a good number of new adds and a few updates for APC.

### CODE REVIEW

**Comment by squintfox** [comment]
@ryanmerolle Sorry about that, I considered it but I wasn't sure if that was preferred to fewer PRs total.  If you want me to re-do it, it's not a problem, just let me know.

**Comment by danner26** [comment]
Do you still need this? @squintfox

**Comment by squintfox** [comment]
@danner26 I don't really need it anymore, we went our own way when I couldn't get it merged.  If it's still useful I can fix it up or whatever you need.

**Comment by danner26** [comment]
If you still want to contribute we would be happy to review it again. The original maintainers are busy but I am here to make sure the PRs get worked on
If you would like to contribute please feel free to reopen this PR, update your branch against our master, and then fix any issues. From there I will review it

**Pull request closed without merging**
