### PR TITLE
Create S6730-H28Y4C.yaml

### PR DESCRIPTION
**Pull request by grbeneke**
Add Huawei CloudEngine S6730-H28Y4C

### CODE REVIEW

**Comment by danner26** [comment]
@grbeneke by default, out of the box are these actually/configured `25gbase-x-sfpp` or `25gbase-x-sfp28`?

**Comment by grbeneke** [comment]
@danner26 that was a typo. Second commit corrects the error.

**Comment by danner26** [comment]
It looks like the power supplies are modular? If this is the case, please make the psu slots module bays instead, and then model the PSUs themselves as module types, if they havent already been. If you have any questions let me know!

**Comment by grbeneke** [comment]
@danner26 template has been changed to module-bays for power

**Pull request merged**
