### PR TITLE
Adding Brand-Rex Patch Panels and Keystone Modules

### PR DESCRIPTION
**Pull request by arcticash**
Created a popular Brand-Rex patch panel and its associated Keystone Modules

### CODE REVIEW

**Comment by arcticash** [comment]
@DanSheps I noticed you have marked the pull request as Revisions Needed but I am not sure what needs revising, are you able to expand on what needs updating?

**Comment by DanSheps** [comment]
This is still marked as a draft PR, so you need to at least move it to a non-draft state.

**Comment by arcticash** [comment]
> This is still marked as a draft PR, so you need to at least move it to a non-draft state.

Ahh okay, I have updated the status now, the "1 workflow awaiting approval" message from GitHub was making me think I needed to wait for something to be accepted before progressing from a draft :)

**Comment by arcticash** [comment]
I have now made some changes based on the failed tests (sorry totally lost track of this PR) ... Is anyone able to re-open the Pull Request or should I submit a new one?

**Comment by arcticash** [comment]
Re-submitted as PR#950

**Pull request closed without merging**
