### PR TITLE
Update Airflow for ICX 7150-C12P-2x10GR

### PR DESCRIPTION
**Pull request by Wlanfr3ak**

### CODE REVIEW

**Comment by danner26** [comment]
@Wlanfr3ak Can you also add `power-ports` if applicable?

**Comment by Wlanfr3ak** [comment]
Its all under: https://github.com/Wlanfr3ak/devicetype-library/blob/master/device-types/Ruckus/icx7150-c12p-2x10gr.yaml and i only added the airflow detail.

**Comment by Wlanfr3ak** [comment]
Originallink: https://github.com/netbox-community/devicetype-library/blob/master/device-types/Ruckus/icx7150-24-2x10g.yaml

**Comment by danner26** [comment]
My bad, I didnt see the expansion section. Ill merge this soon @Wlanfr3ak

**Pull request merged**
