### PR TITLE
Add missing Catalyst 9200/9300 series

### PR DESCRIPTION
**Pull request by bsmeding**
Adding Catalyst 9200/9300    S type versions

### CODE REVIEW

**Comment by danner26** [comment]
Hello, unfortunately we introducted a regression that caused an issue with the pickle files. Could you please review the last commit which was made in error? Thank you.

**Review by bsmeding — COMMENTED** [review]
removed notes

**Comment by danner26** [comment]
You should not be comitting the pickle files, please remove these from your PR

**Comment by bsmeding** [comment]
Didn't saw those files added to my PR, will remove them

**Comment by bsmeding** [comment]
There were created automatically by Github actions by a PR. I don't know how to delete those created files as this is outside my PR

**Pull request closed without merging**
