### PR TITLE
Create Extreme Networks X460-G2 series components

### PR DESCRIPTION
**Pull request by patrickhanft**
This PR creates some Extreme Networks X460-G2 series components, including:

* X460-G2-24t-10GE4
* X460-G2-48p-10GE4
* X460-G2_VIM-2x
* 715W_AC_PSU_FB

As this is my first contribution to this project, I'm trying to get some experience (not a regular Github contributer yet), therefore starting with two switches, an expansion module and a PSU component, eventually trying to add some other (not all!) components from this series later.

### CODE REVIEW

**Comment by patrickhanft** [comment]
Okay, do I wait for someone to approve workflow run, or do I need to mark it as ready for review?

**Comment by patrickhanft** [comment]
I do hope, this removal of the empty `allocated_draw` line fixes the failed test.

**Comment by ryanmerolle** [comment]
Is the PR ready for review?  It still seems in draft.

**Comment by patrickhanft** [comment]
> Is the PR ready for review? It still seems in draft.

It is now. For me as a first time contributor, the tests were not run automatically, I had to wait for someone to start them. I only just have seen that checks have passed.

**Comment by ryanmerolle** [comment]
Yea it’s just a first time contributor gatekeeping function that GitHub put in place recently.

Keeping a PR in draft signals to a project that you would like to wait for it to be merged.

**Pull request merged**
