### PR TITLE
Create TL-SG108E.yaml

### PR DESCRIPTION
**Pull request by jeffersonraimon**

### CODE REVIEW

**Comment by danner26** [comment]
@jeffersonraimon please add the power port(s) as applicable
Also this is not a rack mounted device, please correct me if I am wrong. In that case please change `u_height` to `0`

**Comment by jeffersonraimon** [comment]
Down, check again, pls

**Comment by jeffersonraimon** [comment]
@danner26

**Comment by danner26** [comment]
@jeffersonraimon please correct the power port type, this unit uses an external power adapter that delivers DC current. So please make the type `dc-terminal`

**Comment by jeffersonraimon** [comment]
Done

**Comment by jeffersonraimon** [comment]
@danner26

**Pull request merged**
