### PR TITLE
changes manufacturer "Tripp Lite" to "Eaton"

### PR DESCRIPTION
**Pull request by gurubert**
Tripp Lite is a brand of Eaton, files are in the Eaton directory

### CODE REVIEW

**Comment by harryajc** [comment]
HI @gurubert 
The slugs also need updating to follow the standard naming

**Comment by danner26** [comment]
I seem to see these are still branded as Tripp Lite, is that correct?

If so, we have reviewed this in the past, and if the manufacturer/brand is still Tripp Lite (even if the owning company is Eaton), we will leave the branding as Tripp Lite unless they change the branding completely to Eaton

If there is an identical product number for Eaton, then this should be duplicated into the Eaton folder. Let me know if you have any questions

**Comment by danner26** [comment]
I am going to reject and close this PR for the reason stated above. If you feel this is incorrect, please feel free to inform us as to why and reopen. Thank you.

**Comment by gurubert** [comment]
I have now moved the two files. The importer https://github.com/netbox-community/Device-Type-Library-Import takes the manufacturer name from the directory. The directory name has to match.

**Pull request closed without merging**
