### PR TITLE
Add CryptoPro manufacturer. NGATE-320 and NGATE-600 models.

### PR DESCRIPTION
**Pull request by amdei**
Add CryptoPro manufacturer.
Add NGATE-320 and NGATE-600 device models.

### CODE REVIEW

**Comment by amdei** [comment]
Any chances to get it merged?
Should I fix something, or just create a new PR?

**Comment by danner26** [comment]
Hello @amdei this PR was closed automatically. I just reopened it for you. Sorry about that

Lets have the validations actions run and see where it is at

**Comment by danner26** [comment]
@amdei Looks like everything is good to go, can you please mark this as ready for review and tag me once you are ready?

**Comment by amdei** [comment]
Thanks!

**Pull request merged**
